using Microsoft.EntityFrameworkCore.Migrations;

namespace backend.Migrations
{
    public partial class artistsdescription2 : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "ArtistTranslation",
                keyColumn: "Id",
                keyValue: 13L,
                columns: new[] { "Description", "SourceLink" },
                values: new object[] { "Erasmus Quellinus II is een Antwerpse schilder, tekenaar, graveur en ontwerper van tapijten. Hij stamt uit een kunstenaarsfamilie. Zijn vader is de beeldhouwer Erasmus Quellinus I (1584-1640). Hij is de broer van beeldhouwer Artus Quellinus I (1609-1668) en de graveur Hubertus Quellinus (1619-1687). Quellinus is de vader en de leermeester van de schilder Jan Erasmus Quellinus (1634-1715).Quellinus is een pictor doctus en in die zin vergelijkbaar met Peter Paul Rubens met wie hij vaak samenwerkt in de jaren 1630 en door wie hij beïnvloed wordt. Beiden bezitten een uitgebreide bibliotheek en kunstverzameling. In de geest van het humanisme schrijft Quellinus het filosofisch traktaat Philosophiae, dat niet overgeleverd is. De kunstenaar zou ook een academische graad in de filosofie behaald hebben.Quellinus is verantwoordelijk voor het ontwerp en deels voor de uitvoering van belangrijke decoratieve programma's in het kader van officiële huldigingen in Antwerpen. De kunstenaar werkt ook samen met stillevenspecialisten, onder wie de bloemenschilder Daniël Seghers (1590-1661).Erasmus Quellinus II vervaardigt vele altaarstukken die in de invloedssfeer van de contrareformatie moeten geplaatst worden, maar ook historiestukken en mythologische en allegorische schilderijen. Niettegenstaande de grote invloed van Rubens ontwikkelt Quellinus vroeg in zijn carrière een eigen stijl met sterk door het licht gemodelleerde vormen. Het is mogelijk dat Quellinus die caravaggistische aspecten leert kennen via het werk van Theodoor Rombouts (1597-1637) en Gerard Seghers (1591-1651).Vanaf circa 1640 worden zijn figuren sculpturaal en driedimensionaal, en lijken op geschilderde beelden. Hiermee krijgt zijn werk aansluiting bij het oeuvre van Annibale Carracci (1560-1690), of de classicistische tak van de barok. Quellinus reist nooit naar Italië, maar leert het Romeinse classicisme via zijn broer en beeldhouwer Artus Quellinus I, die een tijd in Rome verblijft, kennen.Na circa 1650 evolueert het barokke classicisme naar een eerder rigide academisme. Quellinus ontwikkelt een voorliefde voor breed uitgesponnen architecturale achtergrondsettings, zoals in werken als Salomon en de Koningin van Sheba. (Sammlungen des Fürsten von Liechtenstein, Vaduz) of Laat de kinderen tot mij komen. (Koninklijke Musea voor Schone Kunsten van België, Brussel)Erasmus Quellinus II sterft als een rijk en beroemd kunstenaar.", "https://vkc-barok-prod.inuits.eu/nl/kunstenaar/erasmus-quellinus-ii" });

            migrationBuilder.UpdateData(
                table: "ArtistTranslation",
                keyColumn: "Id",
                keyValue: 14L,
                columns: new[] { "Description", "SourceLink" },
                values: new object[] { "Erasmus Quellinus II is an Antwerp painter, draftsman, engraver and tapestry designer. He comes from an artistic family. His father is the sculptor Erasmus Quellinus I (1584-1640). He is the brother of the sculptor Artus Quellinus I (1609-1668) and the engraver Hubertus Quellinus (1619-1687). Quellinus is the father and master instructor of the painter Jan Erasmus Quellinus (1634-1715).Quellinus is a pictor doctus and in that sense is comparable to Peter Paul Rubens with whom he often collaborated in the 1630's and by whom he was influenced. Both possess an extensive library and art collection. In the spirit of Humanism, Quellinus writes the philosophical treatise, Philosophae, which has not survived. The artist also would have obtained an academic degree in Philosophy.Quellinus is responsible for the design and in part for the execution of important decorative programmes in the context of official honourings in Antwerp. The artist also worked together with still-life specialists, amongst whom is the floral painter Daniël Seghers (1590-1661).Erasmus Quellinus II made many altarpieces, which need to be placed within the sphere of influence of the Counter Reformation, but also history pieces and mythological and allegorical paintings. The significant influence of Rubens notwithstanding, Quellinus develops early in his career his own style with forms strongly modeled by the light. It is possible that Quellinus learned the Caravaggio-esque aspects via the work of Theodoor Rombouts (1597-1637) and Gerard Seghers (1591-1651).Starting about 1640, his figures become sculptural and three-dimensional and resemble painted sculptures. With this, his work is connected with the oeuvre of Annibale Carracci (1560-1690), or the Classicist branch of the Baroque. Quellinus travels to Italy, but learns about Roman Classicism via his brother and sculptor Artus Quellinus I, who spent some time in Rome.After about 1650, the Baroque Classicism evolves towards a rather rigid academicism. Quellinus develops a preference for broad, expansive architectural background settings, such as in works like Solomon and the Queen of Sheba, (Sammlungen des Fürsten von Liechtenstein, Vaduz), or Suffer the little Children to Come unto Me (Royal Museums of Fine Arts of Belgium, Brussels).Erasmus Quellinus II dies as a rich and famous artist.", "https://vkc-barok-prod.inuits.eu/en/artist/erasmus-quellinus-ii" });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "ArtistTranslation",
                keyColumn: "Id",
                keyValue: 13L,
                columns: new[] { "Description", "SourceLink" },
                values: new object[] { "Artus Quellinus II is een beeldhouwer en stamt uit een kunstenaarsfamilie. Hij is een neef van Artus Quellinus I (1609-1668). In diens atelier geniet hij zijn opleiding. De beeldhouwer krijgt veel opdrachten in de Zuidelijke Nederlanden, maar er is ook vraag vanuit de culturele centra in Europa, zoals Kopenhagen.Artus Quellinus II werkt dramatischer en expressiever dan Artus Quellinus I. Het benadrukken van het emotionele verraadt een link met het werk van Lucas Faydherbe (1617-1697). Quellinus heeft een voorliefde voor gracieuze lichamen, golvende draperieën, en haar dat door de wind beroerd wordt.Na 1670 is de invloed van Gianlorenzo Bernini (1598-1680) duidelijk merkbaar en heeft zijn werk (Bijvoorbeeld de beeldengroep God de vader in de Sint-Salvatorkathedraal in Brugge) een expressief en heroïsch karakter. Een uitgesproken voorbeeld van het theatrale en zeer decoratieve in zijn oeuvre is De apotheose van Sint-Jan (Sint-Jacobskerk, Antwerpen). De invloed van de hoogbarok van Gianlorenzo Bernini is hier bijzonder manifest. De Salomonszuilen met getordeerde schacht en de radiale stralen zijn ontleend aan Bernini's baldakijn in de Sint-Pietersbasiliek in Rome. Quellinus' ontwerp betekent de introductie van een nieuw soort vrijstaand altaar.Het beeld de Heilige Rosa van Lima (Sint-Pauluskerk, Antwerpen) is een voorbeeld van Quellinus' contemplatieve stijl en wordt beschouwd als een van de mooiste sculpturen uit de barok in de Zuidelijke Nederlanden.", "https://vkc-barok-prod.inuits.eu/nl/kunstenaar/artus-quellinus-ii" });

            migrationBuilder.UpdateData(
                table: "ArtistTranslation",
                keyColumn: "Id",
                keyValue: 14L,
                columns: new[] { "Description", "SourceLink" },
                values: new object[] { "Artus Quellinus II is a sculptor and comes from an artistic family. He is the nephew of Artus Quellinus I (1609-1668). It is in his studio that he receives his training. The sculptor has many commissions in the Southern Netherlands, but there are also requests from the cultural centres of Europe, such as Copenhagen.Artus Quellinus II works more dramatically and more expressively than Artus I. The emphasis on the emotional reveals a link with the work of Lucas Faydherbe (1617-1697). Quellinus has a preference for graceful bodies, flowing draperies and hair that is tussled by the wind.After 1670, the influence of Gianlorenzo Bernini (1598-1680) is clearly noticeable and his work has an expressive and heroic character (for example, the sculpture group, God the Father, in the Saint Salvator Cathedral in Bruges). An explicit example of the theatrical and highly decorative in his work is The Apotheosis of Saint James (Saint James's Church, Antwerp). The influence of the High Baroque of Gianlorenzo Bernini is here especially present. The twisted Solomonic columns and the radial rays are borrowed from Bernini's Baldachin in Saint Peter's Basilica in Rome. Quellinus's design signals the introduction of a new type of freestanding altar.The image of Saint Rosa of Lima (Saint Paul's Church, Antwerp) is an example of Quellinus's contemplative style and is seen as one of the most beautiful sculptures from the Baroque in the Southern Netherlands.", "https://vkc-barok-prod.inuits.eu/en/artist/artus-quellinus-ii" });
        }
    }
}
