// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.DAL;

namespace backend.Migrations
{
    [DbContext(typeof(ExplorerContext))]
    [Migration("20190716132331_add-museum-number")]
    partial class addmuseumnumber
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Models.Artist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthdate");

                    b.Property<string>("Deathdate");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Nationality");

                    b.HasKey("Id");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Birthdate = "1626-01-16",
                            Deathdate = "1699-05-12",
                            FirstName = "Lucas",
                            LastName = "Achtschellinck",
                            Nationality = "Belgian"
                        },
                        new
                        {
                            Id = 2L,
                            Birthdate = "1603-07-01",
                            Deathdate = "1671-03-03",
                            FirstName = "Jacob I",
                            LastName = "Van Oost",
                            Nationality = "Belgian"
                        },
                        new
                        {
                            Id = 3L,
                            Birthdate = "1637",
                            Deathdate = "1713-09-29",
                            FirstName = "Jacob II",
                            LastName = "Van Oost",
                            Nationality = "Belgian"
                        },
                        new
                        {
                            Id = 4L,
                            Birthdate = "1581",
                            Deathdate = "1641",
                            FirstName = "Artus",
                            LastName = "Wolfordt",
                            Nationality = "Spanish Netherlands"
                        },
                        new
                        {
                            Id = 5L,
                            Birthdate = "1607-11-19",
                            Deathdate = "1678-11-11",
                            FirstName = "Erasmus II",
                            LastName = "Quellinus",
                            Nationality = "Spanish Netherlands"
                        },
                        new
                        {
                            Id = 6L,
                            Birthdate = "1618-09-14",
                            Deathdate = "1680-11-30",
                            FirstName = "Peter",
                            LastName = "Lely",
                            Nationality = "Netherlands"
                        });
                });

            modelBuilder.Entity("backend.Models.ArtistTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ArtistId");

                    b.Property<string>("Description");

                    b.Property<long>("LanguageId");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("LanguageId");

                    b.ToTable("ArtistTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ArtistId = 1L,
                            Description = "Lucas Achtschellinck est un peintre brabançon baroque spécialisé dans la peinture de paysages.Il est né à Bruxelles en 1626, fut baptisé le 16 janvier de la même année1 . Il entre dans la guilde des peintres le 29 octobre 1639 comme élève de Pieter van der Borcht2.En 1655, à la mort de Lodewijk de Vadder, il pose sa candidature pour devenir cartonnier privilégié de la ville de Bruxelles3. Un voyage à l'étranger peut être envisagé, puisqu'il n'est admis maître qu'en 16574. En 1659, il reçoit 120 florins pour un tableau exécuté à Sainte Gudule5. En 1660 Corneille de Bie publie le Gulden Cabinet6 dans lequel il décrit le style de Lucas Achtschellinck. En 1662, il reçoit 120 florins pour un tableau exécuté à Sainte Gudule7. En 1671, il collabore avec le peintre malinois Lucas Franchois et est payé pour cela en 16738. Le 13 mai 1674, il épouse Anna Parys à l'église du Finistère à Bruxelles9. En 1687, il est doyen représentant les peintres à la corporation et ce jusqu'en 168910. En 1689, il est exonéré en tant que cartonnier11 En 1681, il est « reconnu » c'est-à-dire : exempté de certaines charges du métier à la condition qu'il ne se livre qu'à des travaux artistiques12. Achtschellick est influencé par le style de Rubens dans la façon de peindre les paysages. Il est également fortement influencé par Jacques d'Arthois. Il peint des paysages forestiers, des églises et des cloîtres, ainsi que des scènes avec des personnages inspirées de la Bible. Achtschellinck est connu pour avoir peint les paysages des œuvres majeures du peintre flamand Gaspard de Crayer (1582-1669).Lucas Achtschellinck est souvent associé à son professeur de peinture Lodewijk de Vadder (1605-1655)13, ainsi qu'à Jacques d'Arthois (1603-1686). En effet, on les appelle les peintres de la Forêt de Soignes.",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ArtistId = 1L,
                            Description = "Lucas Achtschellinck (Brussel, gedoopt 16 januari 1626 - aldaar, begraven 12 mei 1699) was een Brussels landschapschilder uit de baroktijd.Achtschellinck werd op 26 oktober 1639 ingeschreven in de Brusselse schildersgilde als leerling van Peter van der Borcht. Men veronderstelt dat hij tussen 1639 en 1657 veel reisde daar hij pas in 1657 gildemeester werd.Achtschellinck werd sterk beïnvloed door Jacques d'Arthois, een leerling uit de Rubensschool. Hij schilderde vooral grote boslandschappen voor kerken en kloosters. Deze landschappen werden door anderen verder afgewerkt met figuren en gebeurtenissen uit de Bijbel. Achtschellinck schilderde ook verscheidene landschappen in de schilderijen van Gaspar de Crayer. Hij vormde samen met Lodewijk de Vadder en Jacques d'Arthois de zogenaamde Zoniënwoudschilders, de leidende groep van Brusselse landschapschilders van dat moment. Hij werd de leraar van onder andere Theobald Michau.",
                            LanguageId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            ArtistId = 1L,
                            Description = "Lucas Achtschellinck baptized 16 January 1626 – buried 12 May 1699), was a Flemish landscape painter. He is counted among the landscape painters active in Brussels referred to as the School of Painters of the Sonian Forest who all shared an interest in depicting scenes set in the Sonian Forest, which is located near Brussels.He was born in Brussels and was possibly the grandson of the landscape painter Lukas Achtschelling. He was registered in the Brussels Guild of Saint Luke on 26 October 1639 as a pupil of a Pieter van der Borcht. The 17th century Flemish biographer Cornelis de Bie mentioned that Lucas Achtschellinck also studied with the Brussels landscapist Lodewijk de Vadder but this is not confirmed by Guild records. However, stylistically the two artists are quite close.Achtschellinck likely travelled abroad after completing his apprenticeship since he only became a master in the Brussels guild in 1657. On 13 March 1674 he married Anna Parys. He remained active in Brussels and in 1687 he was the deacon of the Brussels guild. He was successfully and employed 8 pupils including Théobald Michau between 1659 and 1686.He died in Brussels.",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            ArtistId = 2L,
                            Description = "Jacob van Oost dit le Vieux, également connu sous le nom de Jacques Van Oost le Vieux, né le 1er juillet 1603 à Bruges où il est mort entre le 1er et le 3 mars 1671, est un peintre flamand. Il est considéré comme étant le principal peintre brugeois du xviie siècle.",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            ArtistId = 2L,
                            Description = "Van Oost was de telg van een uitgebreide Brugse schildersfamilie. Na zijn eerste opleiding, waarschijnlijk bij zijn broer Frans van Oost, verbleef hij in Italië van 1621 tot 1628. Vanaf 1651 bekleedde hij de functie van stadsschilder.Zijn oeuvre is sterk beïnvloed door Caravaggio en de Italiaanse meesters, alsook door Vlaamse kunstenaars als Rubens, Antoon van Dyck en Gaspard de Crayer. Zijn voornaamste werken zijn portretten en religieuze taferelen. Ze worden gekenmerkt door licht-donker-effecten, de realistische voorstelling van de figuren, de persoonlijke kleuren en de stillevenelementen. Boven het hoogaltaar van de Sint-Agathakerk te Landskouter is zijn De verrijzenis van Jezus te zien.Jacob van Oost was getrouwd met Jacquemine van Overdille. Ze kregen een zoon, Martinus. Hij hertrouwde met Maria Tollenaere en ze kregen zes kinderen. Zijn zonen Jacob II van Oost (1639-1713) en Willem van Oost (1651-1686) werden eveneens kunstschilder.Er werd een gedenkplaat aangebracht aan zijn woning, Wapenmakersstraat 3 in Brugge. Brugge heeft ook een Jakob van Ooststraat.",
                            LanguageId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            ArtistId = 2L,
                            Description = "Jacob van Oost or Jacob van Oost the Elder (1603–1671) was a Flemish painter of history paintings and portraits. He was the most important painter of Bruges in the 17th century through his portraits of members of the local bourgeois and his many altarpieces made in the spirit of the Counter Reformation. He also created genre paintings of musicians and card players for the open market.",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            ArtistId = 3L,
                            Description = "Jacob van Oost dit le Jeune, né en 1637 et décédé en 1713 à Bruges, connu aussi comme Jacques Van Oost le Jeune, est un peintre baroque flamand.Élève de son père, Jacob van Oost dit le vieux, à Bruges, il poursuit sa formation à Paris puis Rome. Il s'installe à Lille en Flandre en 1668. Il est l'un des peintres les plus renommés, avec Arnould de Vuez, à œuvrer à Lille durant ces années.Peintre de portraits mais surtout de sujets religieux, il couvre les églises et couvents de la ville de ses œuvres. Il épouse une lilloise, Marie Bourgeois, en 1670. De cette union naissent plusieurs enfants dont Dominique van Oost (1677-1738), peintre comme son père.Devenu veuf, il quitte Lille en 1709, à la suite de la prise de la ville par les armées hollandaises et aux troubles qui s'ensuivent, pour retourner dans sa ville natale à l'abri de la guerre. Il y décède le 29 septembre 1713.De nombreuses œuvres de ce maître flamand sont exposées dans des musées et des édifices religieux à Bruges, Bruxelles, Lille et au Louvre à Paris",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            ArtistId = 3L,
                            Description = "Jacob van Oost the Younger (1639, in Bruges – 1713, in Bruges), was a Flemish Baroque painter.According to the Rijksbureau voor Kunsthistorische Documentatie, he was a pupil of his father Jacob sr. and brother to the painter Willem. He is known for portraits and genre works.",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            ArtistId = 4L,
                            Description = "Artus Wolffort, également connu sous les noms de Wolffordt ou Wolffaert, né en 1581 à Anvers et mort en 1641 dans la même ville, est un peintre baroque flamand.Peu après sa naissance ses parents déménagent à Dordrecht. Le 29 décembre 1603, il devient un membre des guildes de Saint-Luc mais doit les quitter faute de moyens financiers. En 1615, il devient l'assistant d'Otto van Veen à Anvers, puis de Rubens, qui influence son style et ses compositions.Dès 1617, il bénéficie d'importantes commandes, dont les retables de l’Ascension et l'Assomption de la Vierge de l'église Saint-Paul d'Anvers. Son œuvre est cependant principalement constituée de compositions destinées à des particuliers. Il peint essentiellement des œuvres religieuses, comprenant des scènes de la vie du Christ et des pères de l'Église.Plusieurs de ses tableaux ont fait l'objet de plusieurs versions, de qualité inégale, comme ses séries Les douze apôtres, Les quatre évangélistes et Les quatre Pères de l'Église. On peut en déduire que Wolffordt entretient un atelier. Deux de ses assistants, Pieter van Lint et Pieter van Mol, sont même connus pour avoir réalisé des répliques de ses tableaux et ont été tous deux fortement influencés par le peintre.Le fils d'Artus Wolffordt, Jan Baptist Wolfaerts, est également peintre. L'une de ses filles a épousé le peintre Willem van Herp.",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            ArtistId = 4L,
                            Description = "Artus Wolffort (1581-1641), ook Wolffaert genoemd, was een Brabants kunstschilder uit Antwerpen. Zijn werken behoren tot de Vlaamse barokschilderkunst.Hij studeerde eerst in Dordrecht waar zijn familie in 1581 naar was uitgeweken. Bij zijn terugkeer naar Antwerpen rond 1615 studeerde hij bij Otto van Veen en Peter Paul Rubens. Rubens beïnvloedde hem qua compositie en stijl.Wolffort schilderde vooral scènes uit het leven van Christus en de kerkvaders. Pieter van Mol en Pieter van Lint waren twee van zijn leerlingen. Het schilderij Aanbidding van de koningen (zie foto) was een opdracht van het kleermakersambacht van Antwerpen. Het toont de figuren in kostbare gewaden, exuberante hoofddeksels en allerlei dure stoffen. Over de toeschrijving van het schilderij was men het lang oneens. Het kwam op naam van Deodaat del Monte, Pieter van Mol en Pieter van Lint. Recent stilistisch onderzoek schrijft het overtuigend toe aan Wolffort.Het gemeentehuis van Aartselaar (ten zuiden van Antwerpen) wordt weliswaar 'Wolffaertshof' genoemd, doch was niet de residentie van barokschilder Wolffort.",
                            LanguageId = 2L
                        },
                        new
                        {
                            Id = 11L,
                            ArtistId = 4L,
                            Description = "Artus Wolffort, Artus Wolffaert or Artus Wolffaerts[1] (1581–1641) was a Flemish painter known mainly for his history paintings depicting religious and mythological scenes.Artus Wolffort was born in Antwerp and moved with his parents to Dordrecht in the year of his birth. He trained as a painter in Dordrecht where he joined the local Guild of Saint Luke in 1603. He returned to Antwerp around 1615 where he worked as an assistant in the studio of Otto van Veen, one of the teachers of Peter Paul Rubens.[3] During this period he lived in the house of van Veen.[4] He became a member of the Antwerp Guild of Saint Luke in 1617.He married Maria Wandelaer on 8 September 1619. Their son Johannes Artusz (better known as Jan Baptist Wolfaerts) was born in November 1625 and later became a painter.[2] Artus Wolffort likely operated a workshop in Antwerp, which produced various copies of his works.[3] His pupils Pieter van Lint and Pieter van Mol worked for a while as copyists in his workshop.[4]Artus Wolffort was one of the artists who worked on the decorations for the Joyous Entry into Antwerp of the new governor of the Habsburg Netherlands Cardinal-Infante Ferdinand in 1635. Rubens was in overall charge of this project for which Wolffort made decorative paintings after designs by Rubens.[6]His pupils included his son Jan Baptist Wolfaerts, Pieter van Lint, Pieter van Mol and Lucas Smout the Elder. He died in Antwerp.[2]",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 12L,
                            ArtistId = 5L,
                            Description = "Érasme Quellin le Jeune (ou Erasmus Quellinus II, Kwelien, Quellien, Quellincs, Quellingh), né le 19 novembre 1607 à Anvers et mort le 11 novembre 1678 dans cette ville, est un peintre, graveur, dessinateur et concepteur de tapisseries flamand qui travaille dans divers genres, dont la peinture d'histoire, le portrait, les scènes de bataille et peintures animalières. Il est un élève de Pierre Paul Rubens et est l’un des plus proches collaborateurs de Rubens dans les années 1630. Après la mort de Rubens en 1640, il devient l’un des peintres les plus prolifiques et les plus prospères des Pays-Bas méridionaux du xviie siècle.",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            ArtistId = 5L,
                            Description = "Erasmus Quellinus II (Antwerpen, 19 november 1607 - aldaar, 7 november 1678), ook genoemd Erasmus de Jonge, was een bekende Brabantse kunstschilder en kopergraveur uit de Antwerpse kunstenaarsfamilie Quellinus. Hij was de zoon van de beeldhouwer Erasmus Quellinus I. Hij werkte vaak samen met Daniël Seghers. Een van hun gezamenlijke werken hangt in de Pinacoteca Nazionale te Bologna.Erasmus werd geboren in een familie van kunstenaars, hoofdzakelijk beeldhouwers, maar koos als beroep voor het schilderen. Hij had het geluk om één van Peter Paul Rubens' vele leerlingen te worden en vervolgens een van zijn naaste medewerkers. Na zijn opleiding bij Rubens in de jaren 1633 - 1634 werd Erasmus Quellinus II meesterschilder in het Antwerpse Sint-Lucasgilde. Hij was zeer erudiet wat zich manifesteerde in zijn verzorgde stijl en zijn veelzijdige activiteiten. Zijn grondige kennis van de mythologie en filosofie kwam tot uiting in vele van zijn werken. Zijn gevarieerde productie droeg veel bij aan de artistieke uitstraling van Antwerpen.",
                            LanguageId = 2L
                        },
                        new
                        {
                            Id = 14L,
                            ArtistId = 5L,
                            Description = "Erasmus Quellinus the Younger and Erasmus Quellinus II (1607–1678) was a Flemish painter, engraver, draughtsman and tapestry designer who worked in various genres including history, portrait, battle and animal paintings. He was a pupil of Peter Paul Rubens and was one of the closest collaborators of Rubens in the 1630s. Following Rubens’ death in 1640 he became one of the most prolific and successful painters in Flanders.",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 15L,
                            ArtistId = 6L,
                            Description = "Sir Peter Lely, de son vrai nom Pieter Van der Faes, né le 14 septembre 1618 à Soest en Westphalie, mort le 30 novembre 1680 à Londres, est un peintre d'origine néerlandaise. Il a connu une immense popularité comme portraitiste en Angleterre où il s'établit dans les années 1640. C'était aussi un grand amateur d'art, qui possédait une belle collection de dessins d'artistes.",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            ArtistId = 6L,
                            Description = "Peter Lely (Soest (Duitsland), 14 september 1618 – Londen, 30 november 1680) was een Engelse kunstschilder van Nederlandse oorsprong. Hij was de populairste portretschilder in Engeland vanaf ongeveer 1640 tot aan zijn dood. Hij was ook kunstverzamelaar en bezat vooral veel tekeningen van andere kunstenaars.Lely werd geboren als Pieter van der Faes uit Nederlandse ouders in Soest in Westfalen, waar zijn vader een ambtenaar was in dienst van het leger van de keurvorst van Brandenburg. Lely studeerde schilderkunst in Haarlem, waar hij mogelijk bij Pieter de Grebber in de leer is geweest. Hij werd een meester van het Sint-Lucasgilde in Haarlem in 1637. Hij was bekend onder de achternaam 'Lely' (nu en dan gespeld als Lilly) vanwege een lelie op de gevel van het huis waar zijn vader in Den Haag geboren was. Hij arriveerde in Londen rond 1641.",
                            LanguageId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            ArtistId = 6L,
                            Description = "Sir Peter Lely (14 September 1618 – 7 December 1680)[1][2] was a painter of Dutch origin whose career was nearly all spent in England, where he became the dominant portrait painter to the court.Lely was born Pieter van der Faes to Dutch parents in Soest in Westphalia,[3] where his father was an officer serving in the armed forces of the Elector of Brandenburg. Lely studied painting in Haarlem, where he may have been apprenticed to Pieter de Grebber. He became a master of the Guild of Saint Luke in Haarlem in 1637. He is reputed to have adopted the surname 'Lely' (also occasionally spelled Lilly) from a heraldic lily on the gable of the house where his father was born in The Hague.He arrived in London in around 1643,[4] His early English paintings, mainly mythological or religious scenes, or portraits set in a pastoral landscape, show influences from Anthony van Dyck and the Dutch baroque. Lely's portraits were well received, and he succeeded Anthony van Dyck (who had died in 1641) as the most fashionable portrait artist in England. He became a freeman of the Painter-Stainers' Company in 1647 and was portrait artist to Charles I. His talent ensured that his career was not interrupted by Charles's execution, and he served Oliver Cromwell, whom he painted 'warts and all', and Richard Cromwell. In the years around 1650 the poet Sir Richard Lovelace wrote two poems about Lely – Peinture and 'See what a clouded majesty ...'",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 18L,
                            ArtistId = 1L,
                            Description = "Lucas Achtschellinck (* 16. Januar 1626 in Brüssel; † 12. Mai 1699) war ein flämischer Landschaftsmaler.1639 wurde Achtschellinck als Schüler von Peter van der Borcht in die Brüsseler Malergilde aufgenommen und wurde stark beeinflusst von Jacques d’Arthois. 1657 wurde er als Freimeister in Brüssel zugelassen. Seine Bilder zeichnen sich aus durch Großräumigkeit der Bilder, ein kräftiges Grün und eine etwas derbe Formanschauung.Am 13. März 1674 heiratete er Anna Parys.",
                            LanguageId = 4L
                        },
                        new
                        {
                            Id = 19L,
                            ArtistId = 2L,
                            Description = "Jakob van Oost der Ältere (* um 1600 in Brügge; † um 1671 in Brügge) war ein flämischer Maler des Barocks in Brügge. Zu seinem Œuvre zählen Historien- und Porträtgemälde.Am 19. Januar 1619 wurde Jakob van Oost als Lehrling seines Bruders Franz van Oost (1618 Freimeister in Brügge; † um 1625) in der Brügger Malergilde aufgelistet. Zu seinem Frühwerk zählen Kopien der Gemälde Jan van Eycksund Peter Paul Rubens, die 1857 teils als Originale galten. Im Jahr 1621 erfolgte seine Ernennung zum Freimeister. Zeitgemäß studierte er in den 20er Jahren in Italien die von Caravaggio beeinflussten Werke Hannibal/Annibale Carraccis. Nach seiner Rückkehr wurde er ab 1630 ein gefragter Auftragskünstler für Porträts, Historiengemälde und Altarwerke. Im Jahr 1633 fand seine Wahl zum Oberhaupt, dem Dekan der Schildergilde statt. Zu seinen Schülern zählten u. a. seine Söhne Jakob van Oost der Jüngere, der die Schule seines Vaters fortsetzte und Willem van Oost (~8. März 1651 in Brügge; † 31. August 1866 ebenda), der Maler und Dominikanerlaienbruder war.Nach seinen Rubenskopien gelangte er zu seinem eigenen Stil in dunkler und toniger Gesamthaltung. Sein Spätwerk ab 1660 besteht aus schwärzlich getonten Werken. Seine Gemälde finden sich in religiösen Einrichtungen und Sammlungen in Brügge, als auch in belgischem Privatbesitz und in folgenden Museen von Bergues, Berlin, Brüssel, Caen, Dijon, Dünkirchen, Leningrad, Lille, London, Lyon, New York City (Histor.Soc.[1] Kat. 1903 und Metropolitan Museum), Oostende, Paris, Tournai, Valenciennes und Wien.",
                            LanguageId = 4L
                        },
                        new
                        {
                            Id = 20L,
                            ArtistId = 3L,
                            Description = "Jakob van Oost der Jüngere (* 1637 in Brügge; † 29. September 1713 in Brügge) war ein flämischer Maler des Barocks.Zunächst von seinem Vater Jakob van Oost dem Älteren in Brügge ausgebildet, vertiefte er seine Kunststudien zwei Jahre lang in Paris. Anschließend widmete er sich mehrere Jahre der Antike und den alten Meistern in Rom. Nach seiner Rückkehr in Brügge wollte er zwar zurück nach Paris, blieb aber in Lille bei seinen Freunden aus der Studienzeit und lebte seit 1668 für 41 Jahre in dieser nordfranzösischen Stadt.Jakob van Oost der Jüngere wurde in dieser Stadt neben Arnould de Vuezein anerkannter Porträtmaler[1]. Zeitgemäß beinhalteten seine Gemälde religiöse Themen. Im Jahr 1670 heiratete er Marie Bourgeois aus Lille, die ihm unter anderem den Sohn Dominique van Oost gebar, welcher ebenfalls Maler wurde.Im Jahr 1709 verließ er als Folge des Spanischen Erbfolgekriegs Lille und kehrte zum Schutz vor dem Krieg in seine Heimatstadt Brügge zurück, wo er vier Jahre später 76-jährig verstarb.",
                            LanguageId = 4L
                        },
                        new
                        {
                            Id = 21L,
                            ArtistId = 4L,
                            Description = "Artus Wolffordt (* 1581 in Antwerpen; † 1641 ebenda) (auch: Wolfaerts, Wolffort, Wolfert) war ein flämischer Maler.Kurz nach seiner Geburt zogen seine Eltern nach Dordrecht. Am 29. Dezember 1603 wurde er dort Mitglied in der St. Lucasgilde, doch bald wieder aus ihr gestrichen, da er nicht mehr vermögend genug war. 1615 wurde er Assistent von Otto van Veen in Antwerpen. 1617 soll er in der Kathedrale St. Paul in Antwerpen am Altar Die Auferstehung und Mariä Himmelfahrt gemalt haben.In seiner Werkstatt sind zahlreiche Werke mit religiösen Motiven entstanden.Zu seinen Schülern zählten Pieter Van Mol (1599–1650) und Pieter van Lint(1609–1690).",
                            LanguageId = 4L
                        },
                        new
                        {
                            Id = 22L,
                            ArtistId = 5L,
                            Description = "Erasmus Quellinus II., auch Erasmus Quellinus der Jüngere, (* 19. November 1607 in Antwerpen; † 7. November1678 ebenda) war ein flämischer Maler, Schüler von Rubens, und Kupferstecher aus der Antwerpener KünstlerfamilieQuellinus.Er ist Sohn des Bildhauers Erasmus Quellinus I. und Bruder von Artus Quellinus I. und Hubertus Quellinus. Er wurde nach seiner Ausbildung bei Rubens 1633/34 Meister der Antwerpener Lukasgilde. Nach dem Tod von Rubens wurde er Stadtmaler von Antwerpen und überführte die ausgesprochen barocke Kunstauffassung von Rubens in eine eher klassizistisch grundierte Malerei. Gut dokumentieren lässt sich diese Neuorientierung an einem seiner wichtigsten Ausstattungsprojekte, die des Paleis op de Dam in Amsterdam, das er um 1656 zusammen mit seinem Bruder Artus Quellinus I ausstattete.Sein Sohn Jan Erasmus Quellinus ist ebenfalls eine bekannte Persönlichkeit unter den Barockmalern der Spanischen Niederlande. Er führte die Hinwendung des Vaters zu einer eher klassizistischen Kunstströmung in Flandern in das 18. Jahrhundert fort.",
                            LanguageId = 4L
                        },
                        new
                        {
                            Id = 23L,
                            ArtistId = 6L,
                            Description = "Sir Peter Lely (eigentlich Pieter van der Faes, * 14. September 1618 im westfälischen Soest;[1] † 30. November 1680 in London) war ein englischerMaler niederländischer Herkunft.Mit 19 Jahren wurde Lely 1637 Schüler bei Pieter de Grebber in Haarlem. Mit Bürgschaft seines Lehrers de Grebber konnte er auch der Lukasgildebeitreten.1643 ging Lely nach England und ließ sich 1647 in London nieder. Schon bald war er überall im Gespräch, da er seine Porträts ganz im Stil Anthonis van Dycks gestaltete. Da van Dyck vor einigen Jahren gestorben war, schloss Lely mit seinen Bildern eine große Lücke. Darum wurde Lely wahrscheinlich auch die Mitgliedschaft der altehrwürdigen Company of Painter Stainers angeboten.Mit der Zeit wurde Lely, zusammen mit William Dobson, einer der führenden Porträtisten der englischen Revolution unter Oliver Cromwell und der nachfolgenden Herrscher. 1651 bewarb sich Lely für die Gestaltung verschiedener Wandmalereien in Whitehall.Zehn Jahre später berief König Karl II. Lely zu seinem offiziellen Hofmaler. Ein Jahr später, 1662, wurde Lely die britische Staatsbürgerschaft verliehen. In den Jahren 1666 bis 1667 schuf Lely für Anne Hyde eine Serie von Porträts verschiedener Hofdamen; heute noch bekannt unter dem Titel The Windsor Beauties. Fast zeitgleich entstand eine weitere Porträtserie von Admirälen, The Flagmen.Am 11. Januar 1680 wurde Lely von König Karl II. persönlich zum Knight Bachelor („Sir“) geschlagen.[2] Bereits ein Jahr später starb Sir Peter Lely im Alter von 62 Jahren.Nach seiner stark niederländisch beeinflussten Phase gelangte Lely im Alter zu einer gelösten freien Maltechnik. Neben vielen Schülern Lelys sei hier vertretend für alle Nicolas de Largillière genannt.",
                            LanguageId = 4L
                        },
                        new
                        {
                            Id = 24L,
                            ArtistId = 1L,
                            Description = "Lucas Achtschellinck (Bruselas 1626–1699) fue un pintor barroco flamenco, especializado en la pintura de paisaje.Nació en Bruselas donde fue bautizado el 16 de enero de 1605. Entró como aprendiz de Pieter van der Borcht II en 1639 y aprendió la técnica de la pintura de paisaje con Lodewijk de Vadder. En 1657 fue aprobado como maestro en su ciudad natal, donde entre 1687 y 1689 desempeñó el cargo de decano de la corporación. Tuvo como discípulo a Theobald Michau.1 Influido por Jacques d'Arthois, sus paisajes, inspirados en el bosque de Soignes, siguen los efectos atmosféricos de los paisajes de Rubens, amplificando su valor pictórico y decorativo por la utilización de sutiles gradaciones de color.2 De él se conocen algunos paisajes animados con escenas bíblicas pintados para iglesias y conventos y, como en otros casos, es posible que colaborase con otros maestros, a los que pudo proporcionar los fondos de paisaje además de ocuparse en la ejecución de cartones para tapices.",
                            LanguageId = 5L
                        },
                        new
                        {
                            Id = 25L,
                            ArtistId = 2L,
                            Description = "Jacob van Oost I o el Viejo (Brujas, 1603 – 1671), fue un pintor barroco flamenco, especializado en pintura religiosa e historiada y retratos.Nacido en Brujas, donde fue bautizado el 7 de enero de 1603, en octubre de 1621 ingresó en el gremio de San Lucas de su ciudad natal. Inmediatamente debió de marchar a Italia donde fue influido por la pintura caravaggista. De nuevo en Brujas, en 1629 fue elegido vicario del gremio y un año después contrajo matrimonio con Jaquemyne van Overdille, de la que enviudó en 1631, tras dar a luz a su hijo Martín. En 1633 casó en segundas nupcias con María van Tollenaere, con quien tuvo seis hijos, entre ellos el también pintor Jacob van Oost, llamado el joven. Decano del gremio de San Lucas en 1633-1634 y en 1643-1644, en enero de 1662 se le documenta por última vez como vicario de la organización gremial.Tuvo numerosos discípulos trabajando en su taller, entre ellos dos aprendices de origen portugués o español: Franscoeis o Francisco Gomes y Jan o Juan Ramón, documentados en Brujas en 1640 y 1666 respectivamente.Desde su primera obra firmada y fechada, la Adoración de los pastores del Museo del Ermitage(1630), caravaggista en el tratamiento de la luz y en la elección de los tipos populares, Van Oost fue frecuentemente reclamado por las iglesias locales para pintar retablos adaptados a la nueva sensibilidad contrarreformista. La influencia de Caravaggio no fue, no obstante, la única influencia italiana de Van Oost, que derivó tempranamente hacia las formulaciones clasicistas de Domenichino a la vez que aclaraba su paleta.",
                            LanguageId = 5L
                        },
                        new
                        {
                            Id = 26L,
                            ArtistId = 3L,
                            Description = "Jacob van Oost II o el Joven (Brujas, 1639 – 1713) fue un pintor barroco flamenco, especializado en retratos y pintura historiada y de género.Hijo y discípulo de Jacob van Oost el Viejo, nació en Brujas, donde fue bautizado el 11 de febrero de 1639. Tras completar su formación en Roma, en el entorno de Simon Vouet, en 1668 se estableció en Lille donde en 1670 casó con Marie Bourgeois. En Lille trabajó principalmente para las iglesias y conventos de la ciudad —San Carlos Borromeo orando por el fin de la peste y San Antonio de Padua con el Niño Jesús para la iglesia de San Mauricio, la Resurrección de Lázaro para la iglesia de la Magdalena o San Macario de Gante socorriendo a los apestados, pasada al Museo del Louvre— en un estilo suave, influido tanto por el tardobarroco romano como por el clasicismo francés.2 Tras enviudar hacia 1697, en 1708 retornó a Brujas donde falleció el 29 de septiembre de 1713.",
                            LanguageId = 5L
                        },
                        new
                        {
                            Id = 27L,
                            ArtistId = 4L,
                            Description = "Artus Wolffort, Wolfordt o Wolffaert (Amberes, 1581 -1641) fue un pintor barroco flamenco especializado en pintura historiada, principalmente de asunto religioso, aunque también cultivó el paisaje y el retrato.Formado en Dordrecht, ciudad a la que se habían trasladado sus padres cuando apenas contaba un año, en 1616 se encontraba de nuevo en Amberes, trabajando durante un corto espacio de tiempo en el taller de Otto van Veen, uno de los maestros de Rubens. Admitido en el gremio local de San Lucas en 1617, el 8 de septiembre de 1619 contrajo matrimonio con María Vandelaer. Del matrimonio nació en 1625 Jan-Baptiste Wolfaerts, quien llegaría a ser pintor especializado en paisajes y ocasionalmente copista de las obras paternas.Aunque recibió algún encargo importante con destino a la iglesia de San Pablo de Amberes, el grueso de su producción está formado por escenas evangélicas y series de apóstoles, evangelistas y padres de la Iglesia, destinadas a particulares. La abundancia de copias de sus obras y su desigual calidad, ha hecho suponer que se situase a la cabeza de un numeroso taller desde el que atender las demandas del mercado de arte. En él se formaron, además de su hijo, Peter van Lint y Peter van Mol.Su pintura, aunque arraigada en el clasicismo de Otto van Veen, recibe también influencias del más vitalista y animado estilo de Rubens, incluso adaptando composiciones de este al más seco estilo de su maestro.",
                            LanguageId = 5L
                        },
                        new
                        {
                            Id = 28L,
                            ArtistId = 5L,
                            Description = "Erasmus Quellinus II, también llamado Erasmus el Joven(Amberes, 1607- 1678), fue un pintor y dibujante flamenco, miembro de una familia de artistas, principalmente escultores, oficio desempeñado por su padre Erasmus Quellinus I y su hermano, Artus Quellinus.Erasmus se formó inicialmente con su padre, pero habiendo optado por la pintura se inclinó hacia los pintores caravaggistas flamencos como Theodoor Rombouts o Gerard Seghers, para crear mediante el uso de la luz figuras rotundas de modelado escultórico.Hacia 1633 se estableció como maestro pintor independiente, ingresando en el Gremio de San Lucas de su ciudad natal, a la vez que comenzó a colaborar con Rubens, primero en las lujosas arquitecturas efímeras levantadas para conmemorar la «joyeuse entrée» del cardenal-infante don Fernando de Austria en la ciudad de Amberes el 15 de abril de 1635,1 y a continuación en el amplio ciclo de pinturas mitológicas encargadas por Felipe IV para la decoración de la Torre de la Parada, en el que Rubens se encontraba trabajando ya en noviembre de 1636.2 A Quellinus correspondieron en este encargo seis cuadros realizados sobre los bocetos de Rubens, todos ellos conservados en el Museo del Prado. A partir de este momento su pintura se hizo más ampulosa, eligiendo para sus escenas de asunto tanto histórico como mitológico o religioso lujosos fondos arquitectónicos de raíz clasicista.Colaboró también con cierta frecuencia con Daniel Seghers y con su cuñado Jan Philip van Thielen, pintando las figuras de sus célebres guirnaldas florales y, a partir de 1656, con su hermano Artus se encargó de la decoración del nuevo Ayuntamiento de Ámsterdam. Como dibujante proporcionó los diseños para series de tapices, como la dedicada a la historia de la familia Thurn und Taxis.Entre sus discípulos y colaboradores se contó su hijo, Jan Erasmus Quellinus.",
                            LanguageId = 5L
                        },
                        new
                        {
                            Id = 29L,
                            ArtistId = 6L,
                            Description = "Peter Lely (Soest, Westfalia; 14 de septiembre de 1618-Covent Garden, Londres, Inglaterra; 30 de noviembre de 1680) fue un retratista danés, nacido en Soest, Westfalia, cuyo verdadero nombre era Pieter van der Faes.Se formó artísticamente en Haarlem, Países Bajos. En 1641 se estableció en Londres, y poco después recibió el encargo de retratar a los principales personajes de la corte inglesa.Carlos II de Inglaterra le nombró pintor de cámara en 1661 y le armó caballero en 1680.Su pintura, rica sobre todo en el colorido de los elegantes ropajes de los retratados, tiene una clara influencia de Anton van Dyck. La serie de cuadros Bellezas de Windsor (década de 1660) se encuentra en el palacio de Hampton Court, Londres. Otra serie, denominada Almirantes, se conserva en el Museo Marítimo Nacional de Greenwich, Londres.",
                            LanguageId = 5L
                        });
                });

            modelBuilder.Entity("backend.Models.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "FR",
                            Name = "Français"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "NL",
                            Name = "Nederlands"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "EN",
                            Name = "English"
                        },
                        new
                        {
                            Id = 4L,
                            Code = "DE",
                            Name = "Deutsch"
                        },
                        new
                        {
                            Id = 5L,
                            Code = "ES",
                            Name = "Español"
                        });
                });

            modelBuilder.Entity("backend.Models.Movement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Movement");

                    b.HasData(
                        new
                        {
                            Id = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.MovementTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<long>("LanguageId");

                    b.Property<long>("MovementId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MovementId");

                    b.ToTable("MovementTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Le baroque est un mouvement artistique qui trouve son origine en Italie dans des villes telles que Rome, Mantoue, Venise et Florence dès le milieu du xvie siècle et qui se termine au milieu du xviiie siècle. Il y a un âge baroque différent selon les domaines, qu'ils soient intellectuels, historiques ou artistiques. Certains critiques y voient une constante culturelle qui revient tout au long de l'histoire comme l'a écrit Eugenio d'Ors.Le baroque, qui touche tous les domaines, se caractérise par l’exagération du mouvement, la surcharge décorative, les effets dramatiques, la tension, l’exubérance des formes, la grandeur parfois pompeuse et le contraste, ce même contraste dont parlait Philippe Beaussant : l’époque baroque a tenté de dire « un monde où tous les contraires seraient harmonieusement possibles »",
                            LanguageId = 1L,
                            MovementId = 1L,
                            Name = "Baroque"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "De barok is een Europese stijlperiode die aan het begin van de 17e eeuw in Italië tot ontwikkeling kwam en tot in de eerste helft van de 18e eeuw voortduurde, en die zich kenmerkt door overdaad van vorm en heftigheid van gevoelsuitdrukking. De barok kwam tot uiting op alle terreinen van de cultuur, zoals architectuur, tuinarchitectuur, schilderkunst, beeldhouwkunst, literatuur en muziek. Er wordt een onderscheid gemaakt tussen vroeg-, hoog- en laatbarok. De laatbarok wordt ook wel rococo genoemd.",
                            LanguageId = 2L,
                            MovementId = 1L,
                            Name = "Barok (stijlperiode)"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "The Baroque (UK: /bəˈrɒk/, US: /bəˈroʊk/) is a highly ornate and often extravagant style of architecture, music, dance, painting, sculpture and other arts that flourished in Europe from the early 17th until the mid-18th century. It followed Renaissance art and Mannerism and preceded the Rococo (in the past often referred to as 'late Baroque') and Neoclassical styles. It was encouraged by the Catholic Church as a means to counter the simplicity and austerity of Protestant architecture, art and music, though Lutheran Baroque art developed in parts of Europe as well.[1]The Baroque style used contrast, movement, exuberant detail, deep colour, grandeur and surprise to achieve a sense of awe. The style began at the start of the 17th century in Rome, then spread rapidly to France, northern Italy, Spain and Portugal, then to Austria and southern Germany. By the 1730s, it had evolved into an even more flamboyant style, called rocaille or Rococo, which appeared in France and Central Europe until the mid to late 18th century.",
                            LanguageId = 3L,
                            MovementId = 1L,
                            Name = "Baroque"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Als Barock (Maskulinum „der Barock“, oder gleichwertig Neutrum „das Barock“) wird eine Epoche der europäischen Kunstgeschichte bezeichnet, die Ende des 16. Jahrhunderts begann[1] und bis ca. 1760/70 reicht. Es handelt sich nicht um einen völlig einheitlichen Stilbegriff, da es innerhalb des Barockzeitalters gleichzeitig zum Teil sehr verschiedene künstlerische Ausprägungen und Unterströmungen und auch eine Entwicklung gab,[2] nicht zuletzt auch große Unterschiede in verschiedenen Gegenden und Ländern.[3]Eine grobe Unterteilung in drei oder vier Unterepochen ist üblich, deren zeitliche Abgrenzung jedoch nicht völlig eindeutig angegeben werden kann: Frühbarock (bis ca. 1650), Hochbarock (ca. 1650–1700), Spätbarock (ca. 1700–1730)[4] und Rokoko (ca. 1730–1760/70). Gelegentlich werden Spätbarock und Rokoko gleichgesetzt, andererseits wird das Rokoko auch als eigenständige Epoche angesehen.Dem Barock voraus gingen die Epochen der Renaissance und des Manierismus, ihm folgte der Klassizismus.",
                            LanguageId = 4L,
                            MovementId = 1L,
                            Name = "Baroque"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "El Barroco fue un período de la historia en la cultura occidental originado por una nueva forma de concebir el arte (el «estilo barroco») y que, partiendo desde diferentes contextos histórico-culturales, produjo obras en numerosos campos artísticos: literatura, arquitectura, escultura, pintura, música, ópera, danza, teatro, etc. Se manifestó principalmente en la Europa occidental, aunque debido al colonialismo también se dio en numerosas colonias de las potencias europeas, principalmente en Latinoamérica. Cronológicamente, abarcó todo el siglo XVIIy principios del XVIII, con mayor o menor prolongación en el tiempo dependiendo de cada país. Se suele situar entre el Manierismo y el Rococó, en una época caracterizada por fuertes disputas religiosas entre países católicos y protestantes, así como marcadas diferencias políticas entre los Estados absolutistas y los parlamentarios, donde una incipiente burguesía empezaba a poner los cimientos del capitalismo.Como estilo artístico, el Barroco surgió a principios del siglo XVII (según otros autores a finales del XVI) en Italia —período también conocido en este país como Seicento—, desde donde se extendió hacia la mayor parte de Europa. Durante mucho tiempo (siglos XVIII y XIX) el término «barroco» tuvo un sentido peyorativo, con el significado de recargado, engañoso, caprichoso, hasta que fue posteriormente revalorizado a finales del siglo XIX por Jacob Burckhardt y, en el XX, por Benedetto Croce y Eugenio d'Ors. Algunos historiadores dividen el Barroco en tres períodos: «primitivo» (1580-1630), «maduro» o «pleno» (1630-1680) y «tardío» (1680-1750).",
                            LanguageId = 5L,
                            MovementId = 1L,
                            Name = "Barroco"
                        });
                });

            modelBuilder.Entity("backend.Models.Painting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AuthorId");

                    b.Property<float>("Height");

                    b.Property<string>("ImageUrl");

                    b.Property<long>("MovementId");

                    b.Property<long>("MuseumNumber");

                    b.Property<long>("TechniqueId");

                    b.Property<float>("Width");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MovementId");

                    b.HasIndex("TechniqueId");

                    b.ToTable("Painting");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = 1L,
                            Height = 162f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO0004_I",
                            MovementId = 1L,
                            MuseumNumber = 1L,
                            TechniqueId = 1L,
                            Width = 228f,
                            Year = 1699
                        },
                        new
                        {
                            Id = 2L,
                            AuthorId = 2L,
                            Height = 150.5f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO0181_I",
                            MovementId = 1L,
                            MuseumNumber = 2L,
                            TechniqueId = 1L,
                            Width = 255.5f,
                            Year = 1645
                        },
                        new
                        {
                            Id = 3L,
                            AuthorId = 2L,
                            Height = 116f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO0184_I",
                            MovementId = 1L,
                            MuseumNumber = 3L,
                            TechniqueId = 1L,
                            Width = 222f,
                            Year = 1668
                        },
                        new
                        {
                            Id = 4L,
                            AuthorId = 3L,
                            Height = 73f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO0187_I",
                            MovementId = 1L,
                            MuseumNumber = 4L,
                            TechniqueId = 1L,
                            Width = 59f,
                            Year = 1697
                        },
                        new
                        {
                            Id = 5L,
                            AuthorId = 4L,
                            Height = 123.3f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO0374_I",
                            MovementId = 1L,
                            MuseumNumber = 5L,
                            TechniqueId = 1L,
                            Width = 94.2f,
                            Year = 1641
                        },
                        new
                        {
                            Id = 6L,
                            AuthorId = 2L,
                            Height = 106f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO1346_I",
                            MovementId = 1L,
                            MuseumNumber = 6L,
                            TechniqueId = 1L,
                            Width = 83f,
                            Year = 1670
                        },
                        new
                        {
                            Id = 7L,
                            AuthorId = 5L,
                            Height = 220f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/1991_GRO0007_I",
                            MovementId = 1L,
                            MuseumNumber = 7L,
                            TechniqueId = 1L,
                            Width = 240f,
                            Year = 1643
                        },
                        new
                        {
                            Id = 8L,
                            AuthorId = 6L,
                            Height = 76.2f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/2012_GRO0001_I",
                            MovementId = 1L,
                            MuseumNumber = 8L,
                            TechniqueId = 1L,
                            Width = 63.5f,
                            Year = 1652
                        },
                        new
                        {
                            Id = 9L,
                            AuthorId = 2L,
                            Height = 193.5f,
                            MovementId = 1L,
                            MuseumNumber = 9L,
                            TechniqueId = 1L,
                            Width = 275f,
                            Year = 1640
                        });
                });

            modelBuilder.Entity("backend.Models.PaintingAudio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AudioUrl");

                    b.Property<long>("LanguageId");

                    b.Property<string>("Name");

                    b.Property<long>("PaintingId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PaintingId");

                    b.ToTable("PaintingAudio");
                });

            modelBuilder.Entity("backend.Models.PaintingStory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<long>("LanguageId");

                    b.Property<long>("PaintingId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PaintingId");

                    b.ToTable("PaintingStory");
                });

            modelBuilder.Entity("backend.Models.PaintingTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<long>("LanguageId");

                    b.Property<string>("Name");

                    b.Property<long>("PaintingId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PaintingId");

                    b.ToTable("PaintingTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            LanguageId = 1L,
                            Name = "Paysage boisé avec gué",
                            PaintingId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Gezicht op een open plek in het bos, met marktkramers en boeren, nabij een doorwaadbare plaats in een beek. Aan de overkant van het water staat een man met twee paarden. Doorheen de bomen heeft men een doorkijk op een verre, gedeeltelijk beboste achtergrond, waar eveneens mensen te zien zijn. De personages op de voorgrond lijken door Achtschellinck zelf geschilderd te zijn; ze zijn duidelijk verwant aan de figuren van zijn tijd- en stadsgenoot David Teniers de Jongere. Het schilderij vertoont een zeer enge stijlovereenkomst met de andere beboste landschappen van Lucas Achtschellinck in de collectie van het Groeningemuseum",
                            LanguageId = 2L,
                            Name = "Boslandschap met wad",
                            PaintingId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            LanguageId = 3L,
                            Name = "Wooded Landscape with Ford",
                            PaintingId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            LanguageId = 1L,
                            Name = "Portrait d'une famille brugeoise",
                            PaintingId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Description = "De burgerman wijst ostentatief naar het ommeland om onze aandacht te vestigen op zijn bezittingen. Het lage gezichtspunt maakt dat de personages een imposante indruk maken. De familie is onbekend, maar door het herkenbare silhouet van de stad Brugge dient de familie in Brugse context gesitueerd te worden. De leeftijden van de familieleden zijn onopvallend geïntegreerd: bij de man op de hiel van zijn schoen (46), bij de vrouw op haar waaier (26), bij de kleine jongen naast haar op zijn hoedje (3), bij het zittende meisje op het kussen in haar korf (15), bij de jongeman op zijn laars (17), en bij het kindje in de armen van het kindermeisje op het stuk brood in haar handen (1). Uit het grote leeftijdsverschil tussen de echtgenoten enerzijds, en de jonge leeftijd van de vrouw anderzijds, kan afgeleid worden dat de kinderen uit twee huwelijken moeten stammen. Waarschijnlijk zijn alleen de twee kleinste kinderen geboren uit het huwelijk met de hier afgebeelde vrouw. Uiterst links op het schilderij staat een tuinman met een spade over de schouder, afdalend naar de tuin. Zoals bij de meeste familieportretten bevat dit werk een onderliggende symboliek, verwijzend naar liefde, zuiverheid en vruchtbaarheid, als voorwaarden voor een harmonisch gezinsleven. Daarnaast wordt de sociale status van het gezin belicht.  (Naar: H. Vlieghe, Stedelijke Musea Brugge. Catalogus Schilderijen 17de en 18de eeuw, Brugge, 1994, pp. 194-195.)",
                            LanguageId = 2L,
                            Name = "Portret van een Brugse familie",
                            PaintingId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            LanguageId = 3L,
                            Name = "Portrait of a Bruges family",
                            PaintingId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            LanguageId = 1L,
                            Name = "Portrait d’un théologien et son secrétaire",
                            PaintingId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Een theoloog, waarschijnlijk een jezuïet, leest de conciliebesluiten en becommentarieert ze. Zijn seculiere secretaris noteert. Links staat de lezenaar, versierd met een sculptuur van een Calvariegroep, en met deel 36 van de verzamelde conciliebesluiten er op. Rechts een werktafel  met een rijk gekleurd tafelkleed, waaraan de priester en de secretaris zitten. Op de tafel bevinden zich studie-attributen, zoals een wereldbol en een boek. Erachter ziet men een boekenkast met bijbeluitgaven en literatuur op het gebied van theologie, exegese en kerkelijk recht. Zoals vaak, inspireert Van Oost zich ook hier weer op de portretten van Anthony van Dyck.  (Naar: H. Vlieghe, Stedelijke Musea Brugge. Catalogus Schilderijen 17de en 18de eeuw, Brugge, 1994, p. 198; E. Tahon, in: musea@brugge, augustus 2003, pp. 13-14.)",
                            LanguageId = 2L,
                            Name = "Portret van een theoloog met zijn secretaris",
                            PaintingId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            LanguageId = 3L,
                            Name = "Portrait of a Theologue and his Secretary",
                            PaintingId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            LanguageId = 1L,
                            Name = "Portrait d' un homme",
                            PaintingId = 4L
                        },
                        new
                        {
                            Id = 11L,
                            Description = "Borstbeeld van een in het zwart geklede man in driekwartswending. Ovaal schilderij, gevat in een rechthoekige lijst. Af te leiden uit het opschrift op de achterzijde, gaat het hier om een vriend van de kunstenaar. (Naar: H. Vlieghe, Stedelijke Musea Brugge. Catalogus Schilderijen 17de en 18de eeuw, Brugge, 1994, pp. 208.)",
                            LanguageId = 2L,
                            Name = "Portret van een man",
                            PaintingId = 4L
                        },
                        new
                        {
                            Id = 12L,
                            LanguageId = 3L,
                            Name = "Portrait of a Man",
                            PaintingId = 4L
                        },
                        new
                        {
                            Id = 13L,
                            LanguageId = 1L,
                            Name = "Sainte Trinité",
                            PaintingId = 5L
                        },
                        new
                        {
                            Id = 14L,
                            Description = "God de Vader, met tiara op het hoofd, toont Christus, de Zoon, die ostentatief zijn wonden laat zien. Boven beiden zweeft de Helige Geest, in de gedaante van een duif. De hier gevolgde iconografie heeft een oude traditie: uiteindelijk gaat ze terug op Dürers gelijknamige prent uit 1511, die op haar beurt weer vroegere Oud-Nederlandse prototypes reflecteert. Het schilderij werd in het verleden begeschreven als achtereenvolgens een werk van Gerard Seghers, een kopie naar Rubens, van de hand van Nicolaas de Liemaeker, in verband te brengen met Abraham Janssens, en toe te schrijven aan Joos de Momper. De recentste toeschrijving toont aan dat het uit het atelier van de Antwerpse schilder Artus Wolffort zou afkomstig zijn. Dit baseert voornamelijk op de karakteristieke gelaatstypering. Van deze compositie bestaan verschillende versies.",
                            LanguageId = 2L,
                            Name = "Heilige Drievuldigheid",
                            PaintingId = 5L
                        },
                        new
                        {
                            Id = 15L,
                            LanguageId = 3L,
                            Name = "Holy Trinity",
                            PaintingId = 5L
                        },
                        new
                        {
                            Id = 16L,
                            LanguageId = 1L,
                            Name = "Portrait de Fovin de Hasque",
                            PaintingId = 6L
                        },
                        new
                        {
                            Id = 17L,
                            Description = "De schermmeester van de Brugse Sint-Michielsgilde is hier voorgesteld met een degen aan zijn gordel. Met zijn rechterhand houdt hij de schacht van een hellebaard of een standaard vast. Het opschrift luidt: Dit is het beelt van Fovin d'Hasque Schermmeester van Brugghe vaillant / Die alhier ghebracht heeft de olie van [de] H. Walburgis uyt duytslant / 1670. Dit laatste deed De Hasque in 1669, op verzoek van de pastoors, kapelaans en kerkmeesters van Sint-Walburga in Brugge. Hij overleed in datzelfde jaar. Wellicht werd dit portret geschilderd naar aanleiding van zijn dood. (Naar: H. Vlieghe, Stedelijke Musea Brugge. Catalogus Schilderijen 17de en 18de eeuw, Brugge, 1994, p. 204.)",
                            LanguageId = 2L,
                            Name = "Portret van Fovin de Hasque",
                            PaintingId = 6L
                        },
                        new
                        {
                            Id = 18L,
                            LanguageId = 3L,
                            Name = "Portrait of Fovin de Hasque",
                            PaintingId = 6L
                        },
                        new
                        {
                            Id = 19L,
                            LanguageId = 1L,
                            Name = "Achille parmi les filles de Lycomède",
                            PaintingId = 7L
                        },
                        new
                        {
                            Id = 20L,
                            Description = "Aan Thetis was voorspeld dat haar zoon Achilles in de Trojaanse Oorlog zou sneuvelen. Om dit lot te omzeilen, verborg ze hem verkleed als vrouw aan het hof van koning Lycomedes. Voor de Griekse aanvoerders Odysseus en Diomedes was Achilles echter onmisbaar. Ze kwamen zijn schuilplaats te weten, en met een list wilden ze hem ontmaskeren. De twee legeraanvoerders gaven geschenken, waaronder wapens, aan de dochters van Lycomedes, met onder hen de verklede Achilles. Spontaan greep Achilles naar een helm en een zwaard, waardoor hij zichzelf verraadde.Links op het voorplan van het schilderij zijn Odysseus en Diomedes afgebeeld. Eén van hen grijpt Achilles bij zijn mouw, op het moment dat hij een helm past en een wapen grijpt uit de geschenken die rechts in een mand zitten en waarrond de dochters van Lycomedes zich scharen. Het tafereel speelt zich af op een terras, met links een doorkijk naar een tuin. De Antwerpse schilder Erasmus Quellinus II behoorde tot een familie van beeldhouwers, schilders, etsers en houtsnijders. Hij was leerling en medewerker van Peter Paul Rubens, die hij als stadsschilder van Antwerpen opvolgde. (Naar: H. Vlieghe, Stedelijke Musea Brugge. Catalogus Schilderijen 17de en 18de eeuw, Brugge, 1994, p. 143.)",
                            LanguageId = 2L,
                            Name = "Achilles en de dochters van Lycomedes",
                            PaintingId = 7L
                        },
                        new
                        {
                            Id = 21L,
                            LanguageId = 3L,
                            Name = "Achilles among the Daughters of Lycomedes",
                            PaintingId = 7L
                        },
                        new
                        {
                            Id = 22L,
                            LanguageId = 1L,
                            Name = "Portrait de Samuel Crew",
                            PaintingId = 8L
                        },
                        new
                        {
                            Id = 23L,
                            Description = "Het betreft een vroeg portret van Lely ut 1650 van Samuel Crew, of zijn broer Nathaniel Crew, telgen van een belangrijke Engelse familie en beide protestantse priesters. Hun vader John Crew of Stene was lid van het Engelse Parliament en fungeerde tussen 1623 en 1625 als Speaker of the House. Lely wilde met dit portret duidelijk aan de verwachtingen van zijn opdrachtgever en zijn belangrijkste mecenas voldoen. Met grote virtuositeit - waarin reflecties van de portretkunst van Frans Hals zijn te herkennen - schildert Lely de kledij van de jonge heer (vermoedelijk Samuel), met veel aandacht voor de textuur en de lichtinval op het zwarte textiel. Het witte hemd schittert in het midden van de donkere, eerder sombere sfeer van het schilderij. Alleen het gelaat en de haren zijn door de lichtinval duidelijk benadrukt. Gedurfd toont Lely zijn model niet in het centrum van het doek, maar positioneert hij de jongeman net uit de middenas van het schilderij. Op die manier vermijdt hij het formalisme van portretten.",
                            LanguageId = 2L,
                            Name = "Portret van Samuel Crew",
                            PaintingId = 8L
                        },
                        new
                        {
                            Id = 24L,
                            LanguageId = 3L,
                            Name = "Portrait of Samuel Crew",
                            PaintingId = 8L
                        },
                        new
                        {
                            Id = 25L,
                            LanguageId = 1L,
                            Name = "La Vocation de saint Matthieu",
                            PaintingId = 9L
                        },
                        new
                        {
                            Id = 26L,
                            LanguageId = 2L,
                            Name = "Roeping van Mattheüs",
                            PaintingId = 9L
                        },
                        new
                        {
                            Id = 27L,
                            LanguageId = 3L,
                            Name = "The Calling of St Matthew",
                            PaintingId = 9L
                        },
                        new
                        {
                            Id = 28L,
                            LanguageId = 4L,
                            Name = "Waldlandschaft mit Furt",
                            PaintingId = 1L
                        },
                        new
                        {
                            Id = 29L,
                            LanguageId = 4L,
                            Name = "Porträt einer Brüggener Familie",
                            PaintingId = 2L
                        },
                        new
                        {
                            Id = 30L,
                            LanguageId = 4L,
                            Name = "Porträt eines Theologen mit seinem Sekretär",
                            PaintingId = 3L
                        },
                        new
                        {
                            Id = 31L,
                            LanguageId = 4L,
                            Name = "Porträt eines Mannes",
                            PaintingId = 4L
                        },
                        new
                        {
                            Id = 32L,
                            LanguageId = 4L,
                            Name = "Heilige Dreifaltigkeit",
                            PaintingId = 5L
                        },
                        new
                        {
                            Id = 33L,
                            LanguageId = 4L,
                            Name = "Porträt des Fovin de Hasque",
                            PaintingId = 6L
                        },
                        new
                        {
                            Id = 34L,
                            LanguageId = 4L,
                            Name = "Achilles unter den Töchtern des Lycomedes",
                            PaintingId = 7L
                        },
                        new
                        {
                            Id = 35L,
                            LanguageId = 4L,
                            Name = "Porträt des Samuel Crew",
                            PaintingId = 8L
                        },
                        new
                        {
                            Id = 36L,
                            LanguageId = 4L,
                            Name = "Berufung des Hl. Matthäus",
                            PaintingId = 9L
                        },
                        new
                        {
                            Id = 37L,
                            LanguageId = 5L,
                            Name = "Paisaje boscoso con fuerte",
                            PaintingId = 1L
                        },
                        new
                        {
                            Id = 38L,
                            LanguageId = 5L,
                            Name = "Retrato de una familia de Brujas",
                            PaintingId = 2L
                        },
                        new
                        {
                            Id = 39L,
                            LanguageId = 5L,
                            Name = "Retrato de un Teólogo y su secretario",
                            PaintingId = 3L
                        },
                        new
                        {
                            Id = 40L,
                            LanguageId = 5L,
                            Name = "Retrato de un hombre",
                            PaintingId = 4L
                        },
                        new
                        {
                            Id = 41L,
                            LanguageId = 5L,
                            Name = "Santa Trinidad",
                            PaintingId = 5L
                        },
                        new
                        {
                            Id = 42L,
                            LanguageId = 5L,
                            Name = "Retrato de Fovin de Hasque",
                            PaintingId = 6L
                        },
                        new
                        {
                            Id = 43L,
                            LanguageId = 5L,
                            Name = "Achilles entre las hijas de Licomedes",
                            PaintingId = 7L
                        },
                        new
                        {
                            Id = 44L,
                            LanguageId = 5L,
                            Name = "Retrato de Samuel Crew",
                            PaintingId = 8L
                        },
                        new
                        {
                            Id = 45L,
                            LanguageId = 5L,
                            Name = "El llamado de San Mateo",
                            PaintingId = 9L
                        });
                });

            modelBuilder.Entity("backend.Models.Technique", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Technique");

                    b.HasData(
                        new
                        {
                            Id = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.TechniqueTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<long>("LanguageId");

                    b.Property<string>("Name");

                    b.Property<long>("TechniqueId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TechniqueId");

                    b.ToTable("TechniqueTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "La peinture à l'huile est une peinture dont le liant ou véhicule est une huile siccative qui enveloppe complètement les particules de pigment.On appelle aussi « peinture » les travaux d'enduction d'une surface par ce genre de produit. Les autorités normatives françaises demandent qu'on dise peinturage, mais ce terme n'a jamais pris1. La « peinture à l'huile » est donc aussi l'activité de nombreux artistes peintres passés et présents, ainsi qu'une technique picturale.",
                            LanguageId = 1L,
                            Name = "Peinture à l'huile",
                            TechniqueId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Olieverf is een verfsoort, een mengsel van pigment in de vorm van een zeer fijn gekleurd poeder met, als bindmiddel, een plantaardige drogende olie, meestal lijnolie. Olieverf is vanaf de 15e eeuw een belangrijk medium in de schilderkunst. Ze werd voor het eerst gebruikt door de Vlaamse Primitieven.",
                            LanguageId = 2L,
                            Name = "Olieverfschilderij",
                            TechniqueId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Oil paint is a type of slow-drying paint that consists of particles of pigment suspended in a drying oil, commonly linseed oil. The viscosity of the paint may be modified by the addition of a solvent such as turpentine or white spirit, and varnish may be added to increase the glossiness of the dried oil paint film. Oil paints have been used in Europe since the 12th century for simple decoration, but were not widely adopted as an artistic medium until the early 15th century. Common modern applications of oil paint are in finishing and protection of wood in buildings and exposed metal structures such as ships and bridges. Its hard-wearing properties and luminous colors make it desirable for both interior and exterior use on wood and metal. Due to its slow-drying properties, it has recently been used in paint-on-glass animation. Thickness of coat has considerable bearing on time required for drying: thin coats of oil paint dry relatively quickly.",
                            LanguageId = 3L,
                            Name = "Oil paint",
                            TechniqueId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Die Ölmalerei ist die künstlerische Malerei mit Ölfarben und gilt als „klassische Königsdisziplin“ der Kunst, die insbesondere bei Porträt-, Landschafts-, Stillleben- und Genremalerei zur Anwendung kommt. Die Haltbarkeit und Farbbrillanz der Ölmalerei ist unübertroffen. Öl ist als Bindemittel ein Hauptbestandteil der Ölfarbe, woraus sich die Bezeichnung für die Ölmalerei ableitet.",
                            LanguageId = 4L,
                            Name = "Ölmalerei",
                            TechniqueId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Una pintura al aceite es un tipo de pintura de secado lento que consiste de partículas de pigmentos en suspensión en un aceite secante. Las pinturas al aceite han sido utilizadas en Inglaterra desde el siglo XIII para decoración,1​ pero no se popularizaron para usos artísticos sino hasta el siglo XV. Los usos modernos más comunes de pinturas al aceite son la decoración de casas, donde su resistencia y colores luminosos las hacen apropiadas tanto para usos en interiores como en exteriores. Sus propiedades de secado lento han sido aprovechadas recientemente para realizar animación mediante pintura sobre vidrio.Cuando se la utiliza para fines artísticos es llamada pintura al óleo.",
                            LanguageId = 5L,
                            Name = "Pintura al aceite",
                            TechniqueId = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.ArtistTranslation", b =>
                {
                    b.HasOne("backend.Models.Artist", "Artist")
                        .WithMany("Translations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.MovementTranslation", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Movement", "Movement")
                        .WithMany("Translations")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.Painting", b =>
                {
                    b.HasOne("backend.Models.Artist", "Author")
                        .WithMany("paintings")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Movement", "Movement")
                        .WithMany("Paintings")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Technique", "Technique")
                        .WithMany()
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.PaintingAudio", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Painting", "Painting")
                        .WithMany("Audios")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.PaintingStory", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Painting", "Painting")
                        .WithMany("Stories")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.PaintingTranslation", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Painting", "Painting")
                        .WithMany("Translations")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.TechniqueTranslation", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Technique", "Technique")
                        .WithMany("Translations")
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
