// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.DAL;

namespace backend.Migrations
{
    [DbContext(typeof(ExplorerContext))]
    [Migration("20190711135614_paintings-imports")]
    partial class paintingsimports
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("backend.Models.Artist", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Birthdate");

                    b.Property<string>("Deathdate");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Nationality");

                    b.HasKey("Id");

                    b.ToTable("Artist");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Birthdate = "1626-01-16",
                            Deathdate = "1699-05-12",
                            FirstName = "Lucas",
                            LastName = "Achtschellinck",
                            Nationality = "Belgian"
                        },
                        new
                        {
                            Id = 2L,
                            Birthdate = "1603-07-01",
                            Deathdate = "1671-03-03",
                            FirstName = "Jacob I",
                            LastName = "Van Oost",
                            Nationality = "Belgian"
                        },
                        new
                        {
                            Id = 3L,
                            Birthdate = "1637",
                            Deathdate = "1713-09-29",
                            FirstName = "Jacob II",
                            LastName = "Van Oost",
                            Nationality = "Belgian"
                        },
                        new
                        {
                            Id = 4L,
                            Birthdate = "1581",
                            Deathdate = "1641",
                            FirstName = "Artus",
                            LastName = "Wolfordt",
                            Nationality = "Spanish Netherlands"
                        },
                        new
                        {
                            Id = 5L,
                            Birthdate = "1607-11-19",
                            Deathdate = "1678-11-11",
                            FirstName = "Erasmus II",
                            LastName = "Quellinus",
                            Nationality = "Spanish Netherlands"
                        },
                        new
                        {
                            Id = 6L,
                            Birthdate = "1618-09-14",
                            Deathdate = "1680-11-30",
                            FirstName = "Peter",
                            LastName = "Lely",
                            Nationality = "Netherlands"
                        });
                });

            modelBuilder.Entity("backend.Models.ArtistTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("ArtistId");

                    b.Property<string>("Description");

                    b.Property<long>("LanguageId");

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.HasIndex("LanguageId");

                    b.ToTable("ArtistTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            ArtistId = 1L,
                            Description = "Lucas Achtschellinck est un peintre brabançon baroque spécialisé dans la peinture de paysages.Il est né à Bruxelles en 1626, fut baptisé le 16 janvier de la même année1 . Il entre dans la guilde des peintres le 29 octobre 1639 comme élève de Pieter van der Borcht2.En 1655, à la mort de Lodewijk de Vadder, il pose sa candidature pour devenir cartonnier privilégié de la ville de Bruxelles3. Un voyage à l'étranger peut être envisagé, puisqu'il n'est admis maître qu'en 16574. En 1659, il reçoit 120 florins pour un tableau exécuté à Sainte Gudule5. En 1660 Corneille de Bie publie le Gulden Cabinet6 dans lequel il décrit le style de Lucas Achtschellinck. En 1662, il reçoit 120 florins pour un tableau exécuté à Sainte Gudule7. En 1671, il collabore avec le peintre malinois Lucas Franchois et est payé pour cela en 16738. Le 13 mai 1674, il épouse Anna Parys à l'église du Finistère à Bruxelles9. En 1687, il est doyen représentant les peintres à la corporation et ce jusqu'en 168910. En 1689, il est exonéré en tant que cartonnier11 En 1681, il est « reconnu » c'est-à-dire : exempté de certaines charges du métier à la condition qu'il ne se livre qu'à des travaux artistiques12. Achtschellick est influencé par le style de Rubens dans la façon de peindre les paysages. Il est également fortement influencé par Jacques d'Arthois. Il peint des paysages forestiers, des églises et des cloîtres, ainsi que des scènes avec des personnages inspirées de la Bible. Achtschellinck est connu pour avoir peint les paysages des œuvres majeures du peintre flamand Gaspard de Crayer (1582-1669).Lucas Achtschellinck est souvent associé à son professeur de peinture Lodewijk de Vadder (1605-1655)13, ainsi qu'à Jacques d'Arthois (1603-1686). En effet, on les appelle les peintres de la Forêt de Soignes.",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            ArtistId = 1L,
                            Description = "Lucas Achtschellinck (Brussel, gedoopt 16 januari 1626 - aldaar, begraven 12 mei 1699) was een Brussels landschapschilder uit de baroktijd.Achtschellinck werd op 26 oktober 1639 ingeschreven in de Brusselse schildersgilde als leerling van Peter van der Borcht. Men veronderstelt dat hij tussen 1639 en 1657 veel reisde daar hij pas in 1657 gildemeester werd.Achtschellinck werd sterk beïnvloed door Jacques d'Arthois, een leerling uit de Rubensschool. Hij schilderde vooral grote boslandschappen voor kerken en kloosters. Deze landschappen werden door anderen verder afgewerkt met figuren en gebeurtenissen uit de Bijbel. Achtschellinck schilderde ook verscheidene landschappen in de schilderijen van Gaspar de Crayer. Hij vormde samen met Lodewijk de Vadder en Jacques d'Arthois de zogenaamde Zoniënwoudschilders, de leidende groep van Brusselse landschapschilders van dat moment. Hij werd de leraar van onder andere Theobald Michau.",
                            LanguageId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            ArtistId = 1L,
                            Description = "Lucas Achtschellinck baptized 16 January 1626 – buried 12 May 1699), was a Flemish landscape painter. He is counted among the landscape painters active in Brussels referred to as the School of Painters of the Sonian Forest who all shared an interest in depicting scenes set in the Sonian Forest, which is located near Brussels.He was born in Brussels and was possibly the grandson of the landscape painter Lukas Achtschelling. He was registered in the Brussels Guild of Saint Luke on 26 October 1639 as a pupil of a Pieter van der Borcht. The 17th century Flemish biographer Cornelis de Bie mentioned that Lucas Achtschellinck also studied with the Brussels landscapist Lodewijk de Vadder but this is not confirmed by Guild records. However, stylistically the two artists are quite close.Achtschellinck likely travelled abroad after completing his apprenticeship since he only became a master in the Brussels guild in 1657. On 13 March 1674 he married Anna Parys. He remained active in Brussels and in 1687 he was the deacon of the Brussels guild. He was successfully and employed 8 pupils including Théobald Michau between 1659 and 1686.He died in Brussels.",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 4L,
                            ArtistId = 2L,
                            Description = "Jacob van Oost dit le Vieux, également connu sous le nom de Jacques Van Oost le Vieux, né le 1er juillet 1603 à Bruges où il est mort entre le 1er et le 3 mars 1671, est un peintre flamand. Il est considéré comme étant le principal peintre brugeois du xviie siècle.",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 5L,
                            ArtistId = 2L,
                            Description = "Van Oost was de telg van een uitgebreide Brugse schildersfamilie. Na zijn eerste opleiding, waarschijnlijk bij zijn broer Frans van Oost, verbleef hij in Italië van 1621 tot 1628. Vanaf 1651 bekleedde hij de functie van stadsschilder.Zijn oeuvre is sterk beïnvloed door Caravaggio en de Italiaanse meesters, alsook door Vlaamse kunstenaars als Rubens, Antoon van Dyck en Gaspard de Crayer. Zijn voornaamste werken zijn portretten en religieuze taferelen. Ze worden gekenmerkt door licht-donker-effecten, de realistische voorstelling van de figuren, de persoonlijke kleuren en de stillevenelementen. Boven het hoogaltaar van de Sint-Agathakerk te Landskouter is zijn De verrijzenis van Jezus te zien.Jacob van Oost was getrouwd met Jacquemine van Overdille. Ze kregen een zoon, Martinus. Hij hertrouwde met Maria Tollenaere en ze kregen zes kinderen. Zijn zonen Jacob II van Oost (1639-1713) en Willem van Oost (1651-1686) werden eveneens kunstschilder.Er werd een gedenkplaat aangebracht aan zijn woning, Wapenmakersstraat 3 in Brugge. Brugge heeft ook een Jakob van Ooststraat.",
                            LanguageId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            ArtistId = 2L,
                            Description = "Jacob van Oost or Jacob van Oost the Elder (1603–1671) was a Flemish painter of history paintings and portraits. He was the most important painter of Bruges in the 17th century through his portraits of members of the local bourgeois and his many altarpieces made in the spirit of the Counter Reformation. He also created genre paintings of musicians and card players for the open market.",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 7L,
                            ArtistId = 3L,
                            Description = "Jacob van Oost dit le Jeune, né en 1637 et décédé en 1713 à Bruges, connu aussi comme Jacques Van Oost le Jeune, est un peintre baroque flamand.Élève de son père, Jacob van Oost dit le vieux, à Bruges, il poursuit sa formation à Paris puis Rome. Il s'installe à Lille en Flandre en 1668. Il est l'un des peintres les plus renommés, avec Arnould de Vuez, à œuvrer à Lille durant ces années.Peintre de portraits mais surtout de sujets religieux, il couvre les églises et couvents de la ville de ses œuvres. Il épouse une lilloise, Marie Bourgeois, en 1670. De cette union naissent plusieurs enfants dont Dominique van Oost (1677-1738), peintre comme son père.Devenu veuf, il quitte Lille en 1709, à la suite de la prise de la ville par les armées hollandaises et aux troubles qui s'ensuivent, pour retourner dans sa ville natale à l'abri de la guerre. Il y décède le 29 septembre 1713.De nombreuses œuvres de ce maître flamand sont exposées dans des musées et des édifices religieux à Bruges, Bruxelles, Lille et au Louvre à Paris",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 8L,
                            ArtistId = 3L,
                            Description = "Jacob van Oost the Younger (1639, in Bruges – 1713, in Bruges), was a Flemish Baroque painter.According to the Rijksbureau voor Kunsthistorische Documentatie, he was a pupil of his father Jacob sr. and brother to the painter Willem. He is known for portraits and genre works.",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            ArtistId = 4L,
                            Description = "Artus Wolffort, également connu sous les noms de Wolffordt ou Wolffaert, né en 1581 à Anvers et mort en 1641 dans la même ville, est un peintre baroque flamand.Peu après sa naissance ses parents déménagent à Dordrecht. Le 29 décembre 1603, il devient un membre des guildes de Saint-Luc mais doit les quitter faute de moyens financiers. En 1615, il devient l'assistant d'Otto van Veen à Anvers, puis de Rubens, qui influence son style et ses compositions.Dès 1617, il bénéficie d'importantes commandes, dont les retables de l’Ascension et l'Assomption de la Vierge de l'église Saint-Paul d'Anvers. Son œuvre est cependant principalement constituée de compositions destinées à des particuliers. Il peint essentiellement des œuvres religieuses, comprenant des scènes de la vie du Christ et des pères de l'Église.Plusieurs de ses tableaux ont fait l'objet de plusieurs versions, de qualité inégale, comme ses séries Les douze apôtres, Les quatre évangélistes et Les quatre Pères de l'Église. On peut en déduire que Wolffordt entretient un atelier. Deux de ses assistants, Pieter van Lint et Pieter van Mol, sont même connus pour avoir réalisé des répliques de ses tableaux et ont été tous deux fortement influencés par le peintre.Le fils d'Artus Wolffordt, Jan Baptist Wolfaerts, est également peintre. L'une de ses filles a épousé le peintre Willem van Herp.",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 10L,
                            ArtistId = 4L,
                            Description = "Artus Wolffort (1581-1641), ook Wolffaert genoemd, was een Brabants kunstschilder uit Antwerpen. Zijn werken behoren tot de Vlaamse barokschilderkunst.Hij studeerde eerst in Dordrecht waar zijn familie in 1581 naar was uitgeweken. Bij zijn terugkeer naar Antwerpen rond 1615 studeerde hij bij Otto van Veen en Peter Paul Rubens. Rubens beïnvloedde hem qua compositie en stijl.Wolffort schilderde vooral scènes uit het leven van Christus en de kerkvaders. Pieter van Mol en Pieter van Lint waren twee van zijn leerlingen. Het schilderij Aanbidding van de koningen (zie foto) was een opdracht van het kleermakersambacht van Antwerpen. Het toont de figuren in kostbare gewaden, exuberante hoofddeksels en allerlei dure stoffen. Over de toeschrijving van het schilderij was men het lang oneens. Het kwam op naam van Deodaat del Monte, Pieter van Mol en Pieter van Lint. Recent stilistisch onderzoek schrijft het overtuigend toe aan Wolffort.Het gemeentehuis van Aartselaar (ten zuiden van Antwerpen) wordt weliswaar 'Wolffaertshof' genoemd, doch was niet de residentie van barokschilder Wolffort.",
                            LanguageId = 2L
                        },
                        new
                        {
                            Id = 11L,
                            ArtistId = 4L,
                            Description = "Artus Wolffort, Artus Wolffaert or Artus Wolffaerts[1] (1581–1641) was a Flemish painter known mainly for his history paintings depicting religious and mythological scenes.Artus Wolffort was born in Antwerp and moved with his parents to Dordrecht in the year of his birth. He trained as a painter in Dordrecht where he joined the local Guild of Saint Luke in 1603. He returned to Antwerp around 1615 where he worked as an assistant in the studio of Otto van Veen, one of the teachers of Peter Paul Rubens.[3] During this period he lived in the house of van Veen.[4] He became a member of the Antwerp Guild of Saint Luke in 1617.He married Maria Wandelaer on 8 September 1619. Their son Johannes Artusz (better known as Jan Baptist Wolfaerts) was born in November 1625 and later became a painter.[2] Artus Wolffort likely operated a workshop in Antwerp, which produced various copies of his works.[3] His pupils Pieter van Lint and Pieter van Mol worked for a while as copyists in his workshop.[4]Artus Wolffort was one of the artists who worked on the decorations for the Joyous Entry into Antwerp of the new governor of the Habsburg Netherlands Cardinal-Infante Ferdinand in 1635. Rubens was in overall charge of this project for which Wolffort made decorative paintings after designs by Rubens.[6]His pupils included his son Jan Baptist Wolfaerts, Pieter van Lint, Pieter van Mol and Lucas Smout the Elder. He died in Antwerp.[2]",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 12L,
                            ArtistId = 5L,
                            Description = "Érasme Quellin le Jeune (ou Erasmus Quellinus II, Kwelien, Quellien, Quellincs, Quellingh), né le 19 novembre 1607 à Anvers et mort le 11 novembre 1678 dans cette ville, est un peintre, graveur, dessinateur et concepteur de tapisseries flamand qui travaille dans divers genres, dont la peinture d'histoire, le portrait, les scènes de bataille et peintures animalières. Il est un élève de Pierre Paul Rubens et est l’un des plus proches collaborateurs de Rubens dans les années 1630. Après la mort de Rubens en 1640, il devient l’un des peintres les plus prolifiques et les plus prospères des Pays-Bas méridionaux du xviie siècle.",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 13L,
                            ArtistId = 5L,
                            Description = "Erasmus Quellinus II (Antwerpen, 19 november 1607 - aldaar, 7 november 1678), ook genoemd Erasmus de Jonge, was een bekende Brabantse kunstschilder en kopergraveur uit de Antwerpse kunstenaarsfamilie Quellinus. Hij was de zoon van de beeldhouwer Erasmus Quellinus I. Hij werkte vaak samen met Daniël Seghers. Een van hun gezamenlijke werken hangt in de Pinacoteca Nazionale te Bologna.Erasmus werd geboren in een familie van kunstenaars, hoofdzakelijk beeldhouwers, maar koos als beroep voor het schilderen. Hij had het geluk om één van Peter Paul Rubens' vele leerlingen te worden en vervolgens een van zijn naaste medewerkers. Na zijn opleiding bij Rubens in de jaren 1633 - 1634 werd Erasmus Quellinus II meesterschilder in het Antwerpse Sint-Lucasgilde. Hij was zeer erudiet wat zich manifesteerde in zijn verzorgde stijl en zijn veelzijdige activiteiten. Zijn grondige kennis van de mythologie en filosofie kwam tot uiting in vele van zijn werken. Zijn gevarieerde productie droeg veel bij aan de artistieke uitstraling van Antwerpen.",
                            LanguageId = 2L
                        },
                        new
                        {
                            Id = 14L,
                            ArtistId = 5L,
                            Description = "Erasmus Quellinus the Younger and Erasmus Quellinus II (1607–1678) was a Flemish painter, engraver, draughtsman and tapestry designer who worked in various genres including history, portrait, battle and animal paintings. He was a pupil of Peter Paul Rubens and was one of the closest collaborators of Rubens in the 1630s. Following Rubens’ death in 1640 he became one of the most prolific and successful painters in Flanders.",
                            LanguageId = 3L
                        },
                        new
                        {
                            Id = 15L,
                            ArtistId = 6L,
                            Description = "Sir Peter Lely, de son vrai nom Pieter Van der Faes, né le 14 septembre 1618 à Soest en Westphalie, mort le 30 novembre 1680 à Londres, est un peintre d'origine néerlandaise. Il a connu une immense popularité comme portraitiste en Angleterre où il s'établit dans les années 1640. C'était aussi un grand amateur d'art, qui possédait une belle collection de dessins d'artistes.",
                            LanguageId = 1L
                        },
                        new
                        {
                            Id = 16L,
                            ArtistId = 6L,
                            Description = "Peter Lely (Soest (Duitsland), 14 september 1618 – Londen, 30 november 1680) was een Engelse kunstschilder van Nederlandse oorsprong. Hij was de populairste portretschilder in Engeland vanaf ongeveer 1640 tot aan zijn dood. Hij was ook kunstverzamelaar en bezat vooral veel tekeningen van andere kunstenaars.Lely werd geboren als Pieter van der Faes uit Nederlandse ouders in Soest in Westfalen, waar zijn vader een ambtenaar was in dienst van het leger van de keurvorst van Brandenburg. Lely studeerde schilderkunst in Haarlem, waar hij mogelijk bij Pieter de Grebber in de leer is geweest. Hij werd een meester van het Sint-Lucasgilde in Haarlem in 1637. Hij was bekend onder de achternaam 'Lely' (nu en dan gespeld als Lilly) vanwege een lelie op de gevel van het huis waar zijn vader in Den Haag geboren was. Hij arriveerde in Londen rond 1641.",
                            LanguageId = 2L
                        },
                        new
                        {
                            Id = 17L,
                            ArtistId = 6L,
                            Description = "Sir Peter Lely (14 September 1618 – 7 December 1680)[1][2] was a painter of Dutch origin whose career was nearly all spent in England, where he became the dominant portrait painter to the court.Lely was born Pieter van der Faes to Dutch parents in Soest in Westphalia,[3] where his father was an officer serving in the armed forces of the Elector of Brandenburg. Lely studied painting in Haarlem, where he may have been apprenticed to Pieter de Grebber. He became a master of the Guild of Saint Luke in Haarlem in 1637. He is reputed to have adopted the surname 'Lely' (also occasionally spelled Lilly) from a heraldic lily on the gable of the house where his father was born in The Hague.He arrived in London in around 1643,[4] His early English paintings, mainly mythological or religious scenes, or portraits set in a pastoral landscape, show influences from Anthony van Dyck and the Dutch baroque. Lely's portraits were well received, and he succeeded Anthony van Dyck (who had died in 1641) as the most fashionable portrait artist in England. He became a freeman of the Painter-Stainers' Company in 1647 and was portrait artist to Charles I. His talent ensured that his career was not interrupted by Charles's execution, and he served Oliver Cromwell, whom he painted 'warts and all', and Richard Cromwell. In the years around 1650 the poet Sir Richard Lovelace wrote two poems about Lely – Peinture and 'See what a clouded majesty ...'",
                            LanguageId = 3L
                        });
                });

            modelBuilder.Entity("backend.Models.Language", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Language");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "FR",
                            Name = "Français"
                        },
                        new
                        {
                            Id = 2L,
                            Code = "NL",
                            Name = "Nederlands"
                        },
                        new
                        {
                            Id = 3L,
                            Code = "EN",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("backend.Models.Movement", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Movement");

                    b.HasData(
                        new
                        {
                            Id = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.MovementTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<long>("LanguageId");

                    b.Property<long>("MovementId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("MovementId");

                    b.ToTable("MovementTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Le baroque est un mouvement artistique qui trouve son origine en Italie dans des villes telles que Rome, Mantoue, Venise et Florence dès le milieu du xvie siècle et qui se termine au milieu du xviiie siècle. Il y a un âge baroque différent selon les domaines, qu'ils soient intellectuels, historiques ou artistiques. Certains critiques y voient une constante culturelle qui revient tout au long de l'histoire comme l'a écrit Eugenio d'Ors.Le baroque, qui touche tous les domaines, se caractérise par l’exagération du mouvement, la surcharge décorative, les effets dramatiques, la tension, l’exubérance des formes, la grandeur parfois pompeuse et le contraste, ce même contraste dont parlait Philippe Beaussant : l’époque baroque a tenté de dire « un monde où tous les contraires seraient harmonieusement possibles »",
                            LanguageId = 1L,
                            MovementId = 1L,
                            Name = "Baroque"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "De barok is een Europese stijlperiode die aan het begin van de 17e eeuw in Italië tot ontwikkeling kwam en tot in de eerste helft van de 18e eeuw voortduurde, en die zich kenmerkt door overdaad van vorm en heftigheid van gevoelsuitdrukking. De barok kwam tot uiting op alle terreinen van de cultuur, zoals architectuur, tuinarchitectuur, schilderkunst, beeldhouwkunst, literatuur en muziek. Er wordt een onderscheid gemaakt tussen vroeg-, hoog- en laatbarok. De laatbarok wordt ook wel rococo genoemd.",
                            LanguageId = 2L,
                            MovementId = 1L,
                            Name = "Barok (stijlperiode)"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "The Baroque (UK: /bəˈrɒk/, US: /bəˈroʊk/) is a highly ornate and often extravagant style of architecture, music, dance, painting, sculpture and other arts that flourished in Europe from the early 17th until the mid-18th century. It followed Renaissance art and Mannerism and preceded the Rococo (in the past often referred to as 'late Baroque') and Neoclassical styles. It was encouraged by the Catholic Church as a means to counter the simplicity and austerity of Protestant architecture, art and music, though Lutheran Baroque art developed in parts of Europe as well.[1]The Baroque style used contrast, movement, exuberant detail, deep colour, grandeur and surprise to achieve a sense of awe. The style began at the start of the 17th century in Rome, then spread rapidly to France, northern Italy, Spain and Portugal, then to Austria and southern Germany. By the 1730s, it had evolved into an even more flamboyant style, called rocaille or Rococo, which appeared in France and Central Europe until the mid to late 18th century.",
                            LanguageId = 3L,
                            MovementId = 1L,
                            Name = "Baroque"
                        });
                });

            modelBuilder.Entity("backend.Models.Painting", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("AuthorId");

                    b.Property<float>("Height");

                    b.Property<string>("ImageUrl");

                    b.Property<long>("MovementId");

                    b.Property<long>("TechniqueId");

                    b.Property<float>("Width");

                    b.Property<int>("Year");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MovementId");

                    b.HasIndex("TechniqueId");

                    b.ToTable("Painting");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AuthorId = 1L,
                            Height = 162f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO0004_I",
                            MovementId = 1L,
                            TechniqueId = 1L,
                            Width = 228f,
                            Year = 1699
                        },
                        new
                        {
                            Id = 2L,
                            AuthorId = 2L,
                            Height = 150.5f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO0181_I",
                            MovementId = 1L,
                            TechniqueId = 1L,
                            Width = 255.5f,
                            Year = 1645
                        },
                        new
                        {
                            Id = 3L,
                            AuthorId = 2L,
                            Height = 116f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO0184_I",
                            MovementId = 1L,
                            TechniqueId = 1L,
                            Width = 222f,
                            Year = 1668
                        },
                        new
                        {
                            Id = 4L,
                            AuthorId = 3L,
                            Height = 73f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO0187_I",
                            MovementId = 1L,
                            TechniqueId = 1L,
                            Width = 59f,
                            Year = 1697
                        },
                        new
                        {
                            Id = 5L,
                            AuthorId = 4L,
                            Height = 123.3f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO0374_I",
                            MovementId = 1L,
                            TechniqueId = 1L,
                            Width = 94.2f,
                            Year = 1641
                        },
                        new
                        {
                            Id = 6L,
                            AuthorId = 2L,
                            Height = 106f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/0000_GRO1346_I",
                            MovementId = 1L,
                            TechniqueId = 1L,
                            Width = 83f,
                            Year = 1670
                        },
                        new
                        {
                            Id = 7L,
                            AuthorId = 5L,
                            Height = 220f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/1991_GRO0007_I",
                            MovementId = 1L,
                            TechniqueId = 1L,
                            Width = 240f,
                            Year = 1643
                        },
                        new
                        {
                            Id = 8L,
                            AuthorId = 6L,
                            Height = 76.2f,
                            ImageUrl = "http://groeningemuseum.be/collection/work/representation/2012_GRO0001_I",
                            MovementId = 1L,
                            TechniqueId = 1L,
                            Width = 63.5f,
                            Year = 1652
                        },
                        new
                        {
                            Id = 9L,
                            AuthorId = 2L,
                            Height = 193.5f,
                            MovementId = 1L,
                            TechniqueId = 1L,
                            Width = 275f,
                            Year = 1640
                        });
                });

            modelBuilder.Entity("backend.Models.PaintingAudio", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AudioUrl");

                    b.Property<long>("LanguageId");

                    b.Property<string>("Name");

                    b.Property<long>("PaintingId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PaintingId");

                    b.ToTable("PaintingAudio");
                });

            modelBuilder.Entity("backend.Models.PaintingStory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ImageUrl");

                    b.Property<long>("LanguageId");

                    b.Property<long>("PaintingId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PaintingId");

                    b.ToTable("PaintingStory");
                });

            modelBuilder.Entity("backend.Models.PaintingTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<long>("LanguageId");

                    b.Property<string>("Name");

                    b.Property<long>("PaintingId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("PaintingId");

                    b.ToTable("PaintingTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            LanguageId = 1L,
                            Name = "Paysage boisé avec gué",
                            PaintingId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Gezicht op een open plek in het bos, met marktkramers en boeren, nabij een doorwaadbare plaats in een beek. Aan de overkant van het water staat een man met twee paarden. Doorheen de bomen heeft men een doorkijk op een verre, gedeeltelijk beboste achtergrond, waar eveneens mensen te zien zijn. De personages op de voorgrond lijken door Achtschellinck zelf geschilderd te zijn; ze zijn duidelijk verwant aan de figuren van zijn tijd- en stadsgenoot David Teniers de Jongere. Het schilderij vertoont een zeer enge stijlovereenkomst met de andere beboste landschappen van Lucas Achtschellinck in de collectie van het Groeningemuseum",
                            LanguageId = 2L,
                            Name = "Boslandschap met wad",
                            PaintingId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            LanguageId = 3L,
                            Name = "Wooded Landscape with Ford",
                            PaintingId = 1L
                        },
                        new
                        {
                            Id = 4L,
                            LanguageId = 1L,
                            Name = "Portrait d'une famille brugeoise",
                            PaintingId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            Description = "De burgerman wijst ostentatief naar het ommeland om onze aandacht te vestigen op zijn bezittingen. Het lage gezichtspunt maakt dat de personages een imposante indruk maken. De familie is onbekend, maar door het herkenbare silhouet van de stad Brugge dient de familie in Brugse context gesitueerd te worden. De leeftijden van de familieleden zijn onopvallend geïntegreerd: bij de man op de hiel van zijn schoen (46), bij de vrouw op haar waaier (26), bij de kleine jongen naast haar op zijn hoedje (3), bij het zittende meisje op het kussen in haar korf (15), bij de jongeman op zijn laars (17), en bij het kindje in de armen van het kindermeisje op het stuk brood in haar handen (1). Uit het grote leeftijdsverschil tussen de echtgenoten enerzijds, en de jonge leeftijd van de vrouw anderzijds, kan afgeleid worden dat de kinderen uit twee huwelijken moeten stammen. Waarschijnlijk zijn alleen de twee kleinste kinderen geboren uit het huwelijk met de hier afgebeelde vrouw. Uiterst links op het schilderij staat een tuinman met een spade over de schouder, afdalend naar de tuin. Zoals bij de meeste familieportretten bevat dit werk een onderliggende symboliek, verwijzend naar liefde, zuiverheid en vruchtbaarheid, als voorwaarden voor een harmonisch gezinsleven. Daarnaast wordt de sociale status van het gezin belicht.  (Naar: H. Vlieghe, Stedelijke Musea Brugge. Catalogus Schilderijen 17de en 18de eeuw, Brugge, 1994, pp. 194-195.)",
                            LanguageId = 2L,
                            Name = "Portret van een Brugse familie",
                            PaintingId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            LanguageId = 3L,
                            Name = "Portrait of a Bruges family",
                            PaintingId = 2L
                        },
                        new
                        {
                            Id = 7L,
                            LanguageId = 1L,
                            Name = "Portrait d’un théologien et son secrétaire",
                            PaintingId = 3L
                        },
                        new
                        {
                            Id = 8L,
                            Description = "Een theoloog, waarschijnlijk een jezuïet, leest de conciliebesluiten en becommentarieert ze. Zijn seculiere secretaris noteert. Links staat de lezenaar, versierd met een sculptuur van een Calvariegroep, en met deel 36 van de verzamelde conciliebesluiten er op. Rechts een werktafel  met een rijk gekleurd tafelkleed, waaraan de priester en de secretaris zitten. Op de tafel bevinden zich studie-attributen, zoals een wereldbol en een boek. Erachter ziet men een boekenkast met bijbeluitgaven en literatuur op het gebied van theologie, exegese en kerkelijk recht. Zoals vaak, inspireert Van Oost zich ook hier weer op de portretten van Anthony van Dyck.  (Naar: H. Vlieghe, Stedelijke Musea Brugge. Catalogus Schilderijen 17de en 18de eeuw, Brugge, 1994, p. 198; E. Tahon, in: musea@brugge, augustus 2003, pp. 13-14.)",
                            LanguageId = 2L,
                            Name = "Portret van een theoloog met zijn secretaris",
                            PaintingId = 3L
                        },
                        new
                        {
                            Id = 9L,
                            LanguageId = 3L,
                            Name = "Portrait of a Theologue and his Secretary",
                            PaintingId = 3L
                        },
                        new
                        {
                            Id = 10L,
                            LanguageId = 1L,
                            Name = "Portrait d' un homme",
                            PaintingId = 4L
                        },
                        new
                        {
                            Id = 11L,
                            Description = "Borstbeeld van een in het zwart geklede man in driekwartswending. Ovaal schilderij, gevat in een rechthoekige lijst. Af te leiden uit het opschrift op de achterzijde, gaat het hier om een vriend van de kunstenaar. (Naar: H. Vlieghe, Stedelijke Musea Brugge. Catalogus Schilderijen 17de en 18de eeuw, Brugge, 1994, pp. 208.)",
                            LanguageId = 2L,
                            Name = "Portret van een man",
                            PaintingId = 4L
                        },
                        new
                        {
                            Id = 12L,
                            LanguageId = 3L,
                            Name = "Portrait of a Man",
                            PaintingId = 4L
                        },
                        new
                        {
                            Id = 13L,
                            LanguageId = 1L,
                            Name = "Sainte Trinité",
                            PaintingId = 5L
                        },
                        new
                        {
                            Id = 14L,
                            Description = "God de Vader, met tiara op het hoofd, toont Christus, de Zoon, die ostentatief zijn wonden laat zien. Boven beiden zweeft de Helige Geest, in de gedaante van een duif. De hier gevolgde iconografie heeft een oude traditie: uiteindelijk gaat ze terug op Dürers gelijknamige prent uit 1511, die op haar beurt weer vroegere Oud-Nederlandse prototypes reflecteert. Het schilderij werd in het verleden begeschreven als achtereenvolgens een werk van Gerard Seghers, een kopie naar Rubens, van de hand van Nicolaas de Liemaeker, in verband te brengen met Abraham Janssens, en toe te schrijven aan Joos de Momper. De recentste toeschrijving toont aan dat het uit het atelier van de Antwerpse schilder Artus Wolffort zou afkomstig zijn. Dit baseert voornamelijk op de karakteristieke gelaatstypering. Van deze compositie bestaan verschillende versies.",
                            LanguageId = 2L,
                            Name = "Heilige Drievuldigheid",
                            PaintingId = 5L
                        },
                        new
                        {
                            Id = 15L,
                            LanguageId = 3L,
                            Name = "Holy Trinity",
                            PaintingId = 5L
                        },
                        new
                        {
                            Id = 16L,
                            LanguageId = 1L,
                            Name = "Portrait de Fovin de Hasque",
                            PaintingId = 6L
                        },
                        new
                        {
                            Id = 17L,
                            Description = "De schermmeester van de Brugse Sint-Michielsgilde is hier voorgesteld met een degen aan zijn gordel. Met zijn rechterhand houdt hij de schacht van een hellebaard of een standaard vast. Het opschrift luidt: Dit is het beelt van Fovin d'Hasque Schermmeester van Brugghe vaillant / Die alhier ghebracht heeft de olie van [de] H. Walburgis uyt duytslant / 1670. Dit laatste deed De Hasque in 1669, op verzoek van de pastoors, kapelaans en kerkmeesters van Sint-Walburga in Brugge. Hij overleed in datzelfde jaar. Wellicht werd dit portret geschilderd naar aanleiding van zijn dood. (Naar: H. Vlieghe, Stedelijke Musea Brugge. Catalogus Schilderijen 17de en 18de eeuw, Brugge, 1994, p. 204.)",
                            LanguageId = 2L,
                            Name = "Portret van Fovin de Hasque",
                            PaintingId = 6L
                        },
                        new
                        {
                            Id = 18L,
                            LanguageId = 3L,
                            Name = "Portrait of Fovin de Hasque",
                            PaintingId = 6L
                        },
                        new
                        {
                            Id = 19L,
                            LanguageId = 1L,
                            Name = "Achille parmi les filles de Lycomède",
                            PaintingId = 7L
                        },
                        new
                        {
                            Id = 20L,
                            Description = "Aan Thetis was voorspeld dat haar zoon Achilles in de Trojaanse Oorlog zou sneuvelen. Om dit lot te omzeilen, verborg ze hem verkleed als vrouw aan het hof van koning Lycomedes. Voor de Griekse aanvoerders Odysseus en Diomedes was Achilles echter onmisbaar. Ze kwamen zijn schuilplaats te weten, en met een list wilden ze hem ontmaskeren. De twee legeraanvoerders gaven geschenken, waaronder wapens, aan de dochters van Lycomedes, met onder hen de verklede Achilles. Spontaan greep Achilles naar een helm en een zwaard, waardoor hij zichzelf verraadde.Links op het voorplan van het schilderij zijn Odysseus en Diomedes afgebeeld. Eén van hen grijpt Achilles bij zijn mouw, op het moment dat hij een helm past en een wapen grijpt uit de geschenken die rechts in een mand zitten en waarrond de dochters van Lycomedes zich scharen. Het tafereel speelt zich af op een terras, met links een doorkijk naar een tuin. De Antwerpse schilder Erasmus Quellinus II behoorde tot een familie van beeldhouwers, schilders, etsers en houtsnijders. Hij was leerling en medewerker van Peter Paul Rubens, die hij als stadsschilder van Antwerpen opvolgde. (Naar: H. Vlieghe, Stedelijke Musea Brugge. Catalogus Schilderijen 17de en 18de eeuw, Brugge, 1994, p. 143.)",
                            LanguageId = 2L,
                            Name = "Achilles en de dochters van Lycomedes",
                            PaintingId = 7L
                        },
                        new
                        {
                            Id = 21L,
                            LanguageId = 3L,
                            Name = "Achilles among the Daughters of Lycomedes",
                            PaintingId = 7L
                        },
                        new
                        {
                            Id = 22L,
                            LanguageId = 1L,
                            Name = "Portrait de Samuel Crew",
                            PaintingId = 8L
                        },
                        new
                        {
                            Id = 23L,
                            Description = "Het betreft een vroeg portret van Lely ut 1650 van Samuel Crew, of zijn broer Nathaniel Crew, telgen van een belangrijke Engelse familie en beide protestantse priesters. Hun vader John Crew of Stene was lid van het Engelse Parliament en fungeerde tussen 1623 en 1625 als Speaker of the House. Lely wilde met dit portret duidelijk aan de verwachtingen van zijn opdrachtgever en zijn belangrijkste mecenas voldoen. Met grote virtuositeit - waarin reflecties van de portretkunst van Frans Hals zijn te herkennen - schildert Lely de kledij van de jonge heer (vermoedelijk Samuel), met veel aandacht voor de textuur en de lichtinval op het zwarte textiel. Het witte hemd schittert in het midden van de donkere, eerder sombere sfeer van het schilderij. Alleen het gelaat en de haren zijn door de lichtinval duidelijk benadrukt. Gedurfd toont Lely zijn model niet in het centrum van het doek, maar positioneert hij de jongeman net uit de middenas van het schilderij. Op die manier vermijdt hij het formalisme van portretten.",
                            LanguageId = 2L,
                            Name = "Portret van Samuel Crew",
                            PaintingId = 8L
                        },
                        new
                        {
                            Id = 24L,
                            LanguageId = 3L,
                            Name = "Portrait of Samuel Crew",
                            PaintingId = 8L
                        },
                        new
                        {
                            Id = 25L,
                            LanguageId = 1L,
                            Name = "La Vocation de saint Matthieu",
                            PaintingId = 9L
                        },
                        new
                        {
                            Id = 26L,
                            LanguageId = 2L,
                            Name = "Roeping van Mattheüs",
                            PaintingId = 9L
                        },
                        new
                        {
                            Id = 27L,
                            LanguageId = 3L,
                            Name = "The Calling of St Matthew",
                            PaintingId = 9L
                        });
                });

            modelBuilder.Entity("backend.Models.Technique", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Technique");

                    b.HasData(
                        new
                        {
                            Id = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.TechniqueTranslation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<long>("LanguageId");

                    b.Property<string>("Name");

                    b.Property<long>("TechniqueId");

                    b.HasKey("Id");

                    b.HasIndex("LanguageId");

                    b.HasIndex("TechniqueId");

                    b.ToTable("TechniqueTranslation");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "La peinture à l'huile est une peinture dont le liant ou véhicule est une huile siccative qui enveloppe complètement les particules de pigment.On appelle aussi « peinture » les travaux d'enduction d'une surface par ce genre de produit. Les autorités normatives françaises demandent qu'on dise peinturage, mais ce terme n'a jamais pris1. La « peinture à l'huile » est donc aussi l'activité de nombreux artistes peintres passés et présents, ainsi qu'une technique picturale.",
                            LanguageId = 1L,
                            Name = "Peinture à l'huile",
                            TechniqueId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Olieverf is een verfsoort, een mengsel van pigment in de vorm van een zeer fijn gekleurd poeder met, als bindmiddel, een plantaardige drogende olie, meestal lijnolie. Olieverf is vanaf de 15e eeuw een belangrijk medium in de schilderkunst. Ze werd voor het eerst gebruikt door de Vlaamse Primitieven.",
                            LanguageId = 2L,
                            Name = "olieverfschilderij",
                            TechniqueId = 1L
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Oil paint is a type of slow-drying paint that consists of particles of pigment suspended in a drying oil, commonly linseed oil. The viscosity of the paint may be modified by the addition of a solvent such as turpentine or white spirit, and varnish may be added to increase the glossiness of the dried oil paint film. Oil paints have been used in Europe since the 12th century for simple decoration, but were not widely adopted as an artistic medium until the early 15th century. Common modern applications of oil paint are in finishing and protection of wood in buildings and exposed metal structures such as ships and bridges. Its hard-wearing properties and luminous colors make it desirable for both interior and exterior use on wood and metal. Due to its slow-drying properties, it has recently been used in paint-on-glass animation. Thickness of coat has considerable bearing on time required for drying: thin coats of oil paint dry relatively quickly.",
                            LanguageId = 3L,
                            Name = "Oil paint",
                            TechniqueId = 1L
                        });
                });

            modelBuilder.Entity("backend.Models.ArtistTranslation", b =>
                {
                    b.HasOne("backend.Models.Artist", "Artist")
                        .WithMany("Translations")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.MovementTranslation", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Movement", "Movement")
                        .WithMany("Translations")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.Painting", b =>
                {
                    b.HasOne("backend.Models.Artist", "Author")
                        .WithMany("paintings")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Movement", "Movement")
                        .WithMany("Paintings")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Technique", "Technique")
                        .WithMany()
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.PaintingAudio", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Painting", "Painting")
                        .WithMany("Audios")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.PaintingStory", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Painting", "Painting")
                        .WithMany("Stories")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.PaintingTranslation", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Painting", "Painting")
                        .WithMany("Translations")
                        .HasForeignKey("PaintingId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("backend.Models.TechniqueTranslation", b =>
                {
                    b.HasOne("backend.Models.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("backend.Models.Technique", "Technique")
                        .WithMany("Translations")
                        .HasForeignKey("TechniqueId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
